#!/bin/sh
#DEBUG=-g

css="leisure gaudy thin cthulhu"
js="marked xus storage parse leisure prim replCore browserRepl std notebook jquery-1.7.2.min jquery-ui/js/jquery-ui-1.9.1.custom.min md maps svg parseAst"

while [ $# != 0 ]; do
  if [ "$1" = -g ]; then DEBUG=-g
  elif [ "$1" = -a ]; then ALL=yes
  fi
  shift
done

# if node_modules/coffee-script/bin/coffee -c storage.coffee parse.coffee patterns.coffee leisure.coffee prim.coffee game.coffee md.coffee \

if node_modules/coffee-script/bin/coffee -c uri.coffee storage.coffee parse.coffee leisure.coffee prim.coffee game.coffee md.coffee \
 && node_modules/coffee-script/bin/coffee -c repl.coffee runRepl.coffee testLeisure.coffee replCore.coffee browserRepl.coffee testing.coffee bootLeisure.coffee notebook.coffee scanner.coffee \
 && node runRepl $DEBUG -q -b 0 -c std
then
    mv bootLeisure.js  bootLeisure.js.tmp
    rm -f leisureFiles.css leisureFiles-*.css leisureFiles.js leisureFiles-*.js
    cat <<EOF > bootLeisure.js
(function(){
var Boot = window.Boot = {};
EOF
    for file in $css; do
        cat $file.css >> leisureFiles.css
    done
    cssName=leisureFiles-$(sha256sum leisureFiles.css|awk '{print $1}').css
    mv leisureFiles.css $cssName
    echo "Boot.cssFiles = ['$cssName'];" >> bootLeisure.js
    for file in $js; do
        cat $file.js >> leisureFiles.js
        echo ';' >> leisureFiles.js
    done
    jsName=leisureFiles-$(sha256sum leisureFiles.js|awk '{print $1}').js
    mv leisureFiles.js $jsName
    echo "Boot.jsFiles = ['$jsName'];" >> bootLeisure.js
cat <<EOF >> bootLeisure.js
})();
EOF
    cat bootLeisure.js.tmp >> bootLeisure.js
    rm bootLeisure.js.tmp
    if [ -n "$ALL" ]; then
        node runRepl $DEBUG -c maps
        node runRepl $DEBUG -c svg
        node runRepl $DEBUG -c parseAst
        #node_modules/coffee-script/bin/coffee -c chippy.coffee
        #node runRepl -c -r chippy chip.lsr
        #node_modules/coffee-script/bin/coffee -c coaster.coffee
        #node runRepl -c -r coaster coast.lsr
        node_modules/coffee-script/bin/coffee -c blocky.coffee
        node runRepl $DEBUG -c -r blocky block
    fi
    echo tests...
    node testLeisure
fi
