#!/bin/sh
node_modules/coffee-script/bin/coffee -c leisure.cs prim.cs repl.cs runRepl.cs testLeisure.cs replCore.cs browserRepl.cs pretty.cs testing.cs
node runRepl -q -c -b std
node_modules/coffee-script/bin/coffee -c aux.cs
node testLeisure
