#!/bin/sh
args=""
WAIT="sleep 10"
app=""

while [ $# != 0 ]; do
    case "$1" in
        -w) WAIT=wait
            ;;
        --app) app="--app="
            ;;
        -d) statifyArgs="$statifyArgs $1 $2"
            shift
            ;;
        *) args="$args $1"
            ;;
    esac
    shift
done

if [ -n "$args" ]; then
    set $args
fi

if [ $# != 0 ]; then
    (sleep 1; google-chrome $(for i in $*; do echo "${app}http://localhost:8000/$i"; done))&
fi

#delegated -f -P8080 SERVER=http MOUNT="/* $(pwd)/*" REMITTABLE=file ADMIN=a@b FILETYPE=".svg:I:SVG:image:image/svg+xml"
echo node node_modules/statify/statify $statifyArgs
node node_modules/statify/statify $statifyArgs &
pid=$!
$WAIT
kill $pid
