var _prelude$Blsr = (function(){
var root;

if ((typeof window !== 'undefined' && window !== null) && (!(typeof global !== 'undefined' && global !== null) || global === window)) {
  _prelude$Blsr = root = {};
  global = window;
  module = {};
} else {
  root = typeof exports !== 'undefined' && exports !== null ? exports : this;
  Parse = require('./parse');
  Leisure = require('./leisure');
  Prim = require('./prim');
  
  ReplCore = require('./replCore');
  Repl = require('./repl');
}

Prim.loading('_prelude$Blsr')


var Nil = Parse.Nil;
var cons = Parse.cons;
var primCons = Parse.primCons;
var setType = Parse.setType;
var setDataType = Parse.setDataType;
var define = Parse.define;
var processResult = Repl.processResult;
var setContext = Leisure.setContext;
var funcContext = Leisure.funcContext;
var define = Parse.define;
var wrapContext = Leisure.wrapContext;
var markLeisureErrors = Leisure.markLeisureErrors;

module.exports =   (_defGroup()((function(){return "["}))((function(){return "]"})))
.andThen(
  (_defGroup()((function(){return "concat["}))((function(){return "]"}))))
.andThen(
  (_defToken()((function(){return "|"}))))
.andThen(
  (_defToken()((function(){return ","}))))
.andThen(
  (_defToken()((function(){return "<-"}))))
.andThen(
  (_defToken()((function(){return "::"}))))
.andThenCode(function(){
  _id = Parse.define('id', (function() {var f; return function _id(){return f || (f = (function(_x){return _x();}));}})(), 1, "\\x . x");;
  _flip = Parse.define('flip', (function() {var f; return function _flip(){return f || (f = (Parse.setDataType(function(_f){return Parse.setType(function(_a){return function(_b){return _f()(_b)(_a);};}, 'flip');}, 'flip')));}})(), 1, "\\f . \\a b . f b a");;
  _compose = Parse.define('compose', (function() {var f; return function _compose(){return f || (f = (Parse.setDataType(function(_f){return function(_g){return Parse.setType(function(_x){return _f()((function(){var $m; return (function(){return $m || ($m = (_g()(_x)))})})());}, 'compose');};}, 'compose')));}})(), 2, "\\f g . \\x . f ( g x)");;
  _true = Parse.define('true', (function() {var f; return function _true(){return f || (f = (Parse.setType(function(_a){return function(_b){return _a();};}, 'true')));}})(), 0, "\\a b . a");;
  _false = Parse.define('false', (function() {var f; return function _false(){return f || (f = (Parse.setType(function(_a){return function(_b){return _b();};}, 'false')));}})(), 0, "\\a b . b");;
  _and = Parse.define('and', (function() {var f; return function _and(){return f || (f = (function(_a){return function(_b){return _a()(_b)(_false);};}));}})(), 2, "\\a b . a b false");;
  _or = Parse.define('or', (function() {var f; return function _or(){return f || (f = (function(_a){return _a()(_true);}));}})(), 1, "\\a . a true");;
  _not = Parse.define('not', (function() {var f; return function _not(){return f || (f = (function(_a){return _a()(_false)(_true);}));}})(), 1, "\\a . a false true");;
  _neq = Parse.define('neq', (function() {var f; return function _neq(){return f || (f = (function(_a){return function(_b){return _not()((function(){var $m; return (function(){return $m || ($m = (_eq()(_a)(_b)))})})());};}));}})(), 2, "\\a b . not (eq a b)");;
  _left = Parse.define('left', (function() {var f; return function _left(){return f || (f = (Parse.setDataType(function(_v){return Parse.setType(function(_l){return function(_r){return _l()(_v);};}, 'left');}, 'left')));}})(), 1, "\\v . \\l r . l v");;
  _right = Parse.define('right', (function() {var f; return function _right(){return f || (f = (Parse.setDataType(function(_v){return Parse.setType(function(_l){return function(_r){return _r()(_v);};}, 'right');}, 'right')));}})(), 1, "\\v . \\l r . r v");;
  _some = Parse.define('some', (function() {var f; return function _some(){return f || (f = (Parse.setDataType(function(_x){return Parse.setType(function(_yes){return function(_no){return _yes()(_x);};}, 'some');}, 'some')));}})(), 1, "\\x . \\yes no . yes x");;
  _some2 = Parse.define('some2', (function() {var f; return function _some2(){return f || (f = (Parse.setDataType(function(_a){return function(_b){return Parse.setType(function(_yes){return function(_no){return _yes()(_a)(_b);};}, 'some2');};}, 'some2')));}})(), 2, "\\a b . \\yes no . yes a b");;
  _none = Parse.define('none', (function() {var f; return function _none(){return f || (f = (Parse.setType(function(_yes){return function(_no){return _no();};}, 'none')));}})(), 0, "\\yes no . no");;
  _iszero = Parse.define('iszero', (function _iszero() {return ((_eq()((function(){return 0}))));}), 0, "eq 0");;
  _positive = Parse.define('positive', (function _positive() {return ((_$y()((function(){return 0}))));}), 0, "< 0");;
  _$_$_ = Parse.define('--', (function _$_$_() {return ((_flip()(_$_)((function(){return 1}))));}), 0, "(flip -) 1");;
  _$o$o = Parse.define('++', (function _$o$o() {return ((_$o()((function(){return 1}))));}), 0, "+ 1");;
  _even$e = Parse.define('even?', (function() {var f; return function _even$e(){return f || (f = (function(_x){return _iszero()((function(){var $m; return (function(){return $m || ($m = (_$A()(_x)((function(){return 2}))))})})());}));}})(), 1, "\\x . iszero (% x 2)");;
  _odd$e = Parse.define('odd?', (function() {var f; return function _odd$e(){return f || (f = (function(_x){return _eq()((function(){return 1}))((function(){var $m; return (function(){return $m || ($m = (_$A()(_x)((function(){return 2}))))})})());}));}})(), 1, "\\x . eq 1 (% x 2)");;
  _max = Parse.define('max', (function() {var f; return function _max(){return f || (f = (function(_a){return function(_b){return _gt()(_a)(_b)(_a)(_b);};}));}})(), 2, "\\a b . (gt a b) a b");;
  _min = Parse.define('min', (function() {var f; return function _min(){return f || (f = (function(_a){return function(_b){return _lt()(_a)(_b)(_a)(_b);};}));}})(), 2, "\\a b . (lt a b) a b");;
  _isStream = Parse.define('isStream', (function() {var f; return function _isStream(){return f || (f = (function(_x){return _false();}));}})(), 1, "\\x . false");;
  _isStream = Leisure.makeDispatchFunction('isStream', '_isStream', '_x', ['_isStream', '_x']);
Leisure.createMethod('cons', 'isStream', "\\x       . true", function(_x) {return _true();});
  _isStream = Leisure.makeDispatchFunction('isStream', '_isStream', '_x', ['_isStream', '_x']);
Leisure.createMethod('lexCons', 'isStream', "\\x          . true", function(_x) {return _true();});
  _head = Leisure.makeDispatchFunction('head', '_head', '_l', ['_head', '_l']);
Leisure.createMethod('cons', 'head', "\\l       . l \\h t . h", function(_l) {return _l()((function(){var $m; return (function(){return $m || ($m = (function(_h){return function(_t){return _h();};}))})})());});
  _tail = Leisure.makeDispatchFunction('tail', '_tail', '_l', ['_tail', '_l']);
Leisure.createMethod('cons', 'tail', "\\l       . l \\h t . t", function(_l) {return _l()((function(){var $m; return (function(){return $m || ($m = (function(_h){return function(_t){return _t();};}))})})());});
  _head = Leisure.makeDispatchFunction('head', '_head', '_l', ['_head', '_l']);
Leisure.createMethod('lexCons', 'head', "\\l          . l \\h s t e . h", function(_l) {return _l()((function(){var $m; return (function(){return $m || ($m = (function(_h){return function(_s){return function(_t){return function(_e){return _h();};};};}))})})());});
  _tail = Leisure.makeDispatchFunction('tail', '_tail', '_l', ['_tail', '_l']);
Leisure.createMethod('lexCons', 'tail', "\\l          . l \\h s t e . t", function(_l) {return _l()((function(){var $m; return (function(){return $m || ($m = (function(_h){return function(_s){return function(_t){return function(_e){return _t();};};};}))})})());});
  _length = Parse.define('length', (function() {var f; return function _length(){return f || (f = (function(_l){return _eq()(_l)(_nil)((function(){return 0}))((function(){var $m; return (function(){return $m || ($m = (_$o$o()((function(){var $m; return (function(){return $m || ($m = (_length()((function(){var $m; return (function(){return $m || ($m = (_tail()(_l)))})})())))})})())))})})());}));}})(), 1, "\\l . (eq l nil) 0 (++ (length (tail l) ) )");;
  _last = Parse.define('last', (function() {var f; return function _last(){return f || (f = (function(_l){return _eq()((function(){var $m; return (function(){return $m || ($m = (_tail()(_l)))})})())(_nil)((function(){var $m; return (function(){return $m || ($m = (_head()(_l)))})})())((function(){var $m; return (function(){return $m || ($m = (_last()((function(){var $m; return (function(){return $m || ($m = (_tail()(_l)))})})())))})})());}));}})(), 1, "\\l . eq (tail l) nil\n  head l\n  last (tail l)");;
  _startPos = Leisure.makeDispatchFunction('startPos', '_startPos', '_l', ['_startPos', '_l']);
Leisure.createMethod('lexCons', 'startPos', "\\l          . lexStart l", function(_l) {return _lexStart()(_l);});
  _startPos = Leisure.makeDispatchFunction('startPos', '_startPos', '_t', ['_startPos', '_t']);
Leisure.createMethod('token', 'startPos', "\\t        . t \\t p . p", function(_t) {return _t()((function(){var $m; return (function(){return $m || ($m = (function(_t){return function(_p){return _p();};}))})})());});
  _endPos = Leisure.makeDispatchFunction('endPos', '_endPos', '_l', ['_endPos', '_l']);
Leisure.createMethod('lexCons', 'endPos', "\\l          . lexEnd l", function(_l) {return _lexEnd()(_l);});
  _endPos = Leisure.makeDispatchFunction('endPos', '_endPos', '_t', ['_endPos', '_t']);
Leisure.createMethod('token', 'endPos', "\\t        . + (tokenStart t) (strlen (tokenName t))", function(_t) {return _$o()((function(){var $m; return (function(){return $m || ($m = (_tokenStart()(_t)))})})())((function(){var $m; return (function(){return $m || ($m = (_strlen()((function(){var $m; return (function(){return $m || ($m = (_tokenName()(_t)))})})())))})})());});
  _pairFunc = Parse.define('pairFunc', (function() {var f; return function _pairFunc(){return f || (f = (function(_l){return _false();}));}})(), 1, "\\l . false");;
  _pairFunc = Leisure.makeDispatchFunction('pairFunc', '_pairFunc', '_l', ['_pairFunc', '_l']);
Leisure.createMethod('cons', 'pairFunc', "\\l       . cons", function(_l) {return _cons();});
  _pairFunc = Leisure.makeDispatchFunction('pairFunc', '_pairFunc', '_l', ['_pairFunc', '_l']);
Leisure.createMethod('lexCons', 'pairFunc', "\\l          . lexConsFuzzy", function(_l) {return _lexConsFuzzy();});
  _pairFunc = Leisure.makeDispatchFunction('pairFunc', '_pairFunc', '_l', ['_pairFunc', '_l']);
Leisure.createMethod('token', 'pairFunc', "\\l        . lexConsFuzzy", function(_l) {return _lexConsFuzzy();});
  _lexConsFuzzy = Parse.define('lexConsFuzzy', (function() {var f; return function _lexConsFuzzy(){return f || (f = (function(_h){return function(_t){return _null$e()(_t)((function(){var $m; return (function(){return $m || ($m = (_lexCons()(_h)((function(){var $m; return (function(){return $m || ($m = (_startPos()(_h)))})})())(_nil)((function(){var $m; return (function(){return $m || ($m = (_endPos()(_h)))})})())))})})())((function(){var $m; return (function(){return $m || ($m = (_lexCons()(_h)((function(){var $m; return (function(){return $m || ($m = (_startPos()(_h)))})})())(_t)((function(){var $m; return (function(){return $m || ($m = (_endPos()(_t)))})})())))})})());};}));}})(), 2, "\\h t . null? t\n  lexCons h (startPos h) nil (endPos h)\n  lexCons h (startPos h) t (endPos t)");;
  _null$e = Parse.define('null?', (function() {var f; return function _null$e(){return f || (f = (function(_x){return _false();}));}})(), 1, "\\x . false");;
  _null$e = Leisure.makeDispatchFunction('null?', '_null$e', '_x', ['_null$e', '_x']);
Leisure.createMethod('nil', 'null?', "\\x      . true", function(_x) {return _true();});
  _map = Parse.define('map', (function() {var f; return function _map(){return f || (f = (function(_func){return function(_list){return __map()((function(){var $m; return (function(){return $m || ($m = (_pairFunc()(_list)))})})())(_func)(_list);};}));}})(), 2, "\\func list . _map (pairFunc list) func list");;
  __map = Parse.define('_map', (function() {var f; return function __map(){return f || (f = (function(_pairF){return function(_func){return function(_list){return _null$e()(_list)(_nil)((function(){var $m; return (function(){return $m || ($m = (_pairF()((function(){var $m; return (function(){return $m || ($m = (_func()((function(){var $m; return (function(){return $m || ($m = (_head()(_list)))})})())))})})())((function(){var $m; return (function(){return $m || ($m = (__map()(_pairF)(_func)((function(){var $m; return (function(){return $m || ($m = (_tail()(_list)))})})())))})})())))})})());};};}));}})(), 3, "\\pairF func list . null? list\n  nil\n  pairF (func (head list)) (_map pairF func (tail list))");;
  _foldl = Parse.define('foldl', (function() {var f; return function _foldl(){return f || (f = (function(_func){return function(_arg){return function(_list){return _foldl()(_func)((function(){var $m; return (function(){return $m || ($m = (_func()(_arg)((function(){var $m; return (function(){return $m || ($m = (_head()(_list)))})})())))})})())((function(){var $m; return (function(){return $m || ($m = (_tail()(_list)))})})());};};}));}})(), 3, "\\func arg list . foldl func (func arg (head list)) (tail list)");;
  _foldl = Leisure.makeDispatchFunction('foldl', '_foldl', '_list', ['_foldl', '_func', '_arg', '_list']);
Leisure.createMethod('nil', 'foldl', "\\func arg list      . arg", function(_func, _arg, _list) {return _arg();});
  _foldl1 = Parse.define('foldl1', (function() {var f; return function _foldl1(){return f || (f = (function(_func){return function(_list){return _foldl()(_func)((function(){var $m; return (function(){return $m || ($m = (_head()(_list)))})})())((function(){var $m; return (function(){return $m || ($m = (_tail()(_list)))})})());};}));}})(), 2, "\\func list . foldl func (head list) (tail list)");;
  _foldl1 = Leisure.makeDispatchFunction('foldl1', '_foldl1', '_list', ['_foldl1', '_func', '_list']);
Leisure.createMethod('nil', 'foldl1', "\\func list      . nil", function(_func, _list) {return _nil();});
  _foldr = Parse.define('foldr', (function() {var f; return function _foldr(){return f || (f = (function(_func){return function(_arg){return function(_list){return _null$e()(_list)(_arg)((function(){var $m; return (function(){return $m || ($m = (_func()((function(){var $m; return (function(){return $m || ($m = (_head()(_list)))})})())((function(){var $m; return (function(){return $m || ($m = (_foldr()(_func)(_arg)((function(){var $m; return (function(){return $m || ($m = (_tail()(_list)))})})())))})})())))})})());};};}));}})(), 3, "\\func arg list . null? list\n  arg\n  func (head list) (foldr func arg (tail list))");;
  _foldr1 = Parse.define('foldr1', (function() {var f; return function _foldr1(){return f || (f = (function(_func){return function(_list){return _eq()((function(){var $m; return (function(){return $m || ($m = (_tail()(_list)))})})())(_nil)((function(){var $m; return (function(){return $m || ($m = (_head()(_list)))})})())((function(){var $m; return (function(){return $m || ($m = (_func()((function(){var $m; return (function(){return $m || ($m = (_head()(_list)))})})())((function(){var $m; return (function(){return $m || ($m = (_foldr1()(_func)((function(){var $m; return (function(){return $m || ($m = (_tail()(_list)))})})())))})})())))})})());};}));}})(), 2, "\\func list . eq (tail list) nil\n  head list\n  func (head list) (foldr1 func (tail list))");;
  _foldr1 = Leisure.makeDispatchFunction('foldr1', '_foldr1', '_list', ['_foldr1', '_func', '_list']);
Leisure.createMethod('nil', 'foldr1', "\\func list      . nil", function(_func, _list) {return _nil();});
  _append = Parse.define('append', (function() {var f; return function _append(){return f || (f = (function(_l1){return function(_l2){return __append()((function(){var $m; return (function(){return $m || ($m = (_pairFunc()(_l1)))})})())(_l1)(_l2);};}));}})(), 2, "\\l1 l2 . _append (pairFunc l1) l1 l2");;
  _append = Leisure.makeDispatchFunction('append', '_append', '_l1', ['_append', '_l1', '_l2']);
Leisure.createMethod('nil', 'append', "\\l1      l2 . l2", function(_l1, _l2) {return _l2();});
  __append = Parse.define('_append', (function() {var f; return function __append(){return f || (f = (function(_pairF){return function(_l1){return function(_l2){return _pairF()((function(){var $m; return (function(){return $m || ($m = (_head()(_l1)))})})())((function(){var $m; return (function(){return $m || ($m = (__append()(_pairF)((function(){var $m; return (function(){return $m || ($m = (_tail()(_l1)))})})())(_l2)))})})());};};}));}})(), 3, "\\pairF l1 l2 . pairF (head l1) (_append pairF (tail l1) l2)");;
  __append = Leisure.makeDispatchFunction('_append', '__append', '_l1', ['__append', '_pairF', '_l1', '_l2']);
Leisure.createMethod('nil', '_append', "\\pairF l1      l2 . l2", function(_pairF, _l1, _l2) {return _l2();});
  _reverse = Parse.define('reverse', (function() {var f; return function _reverse(){return f || (f = (function(_l){return _subreverse()(_l)(_nil);}));}})(), 1, "\\l . subreverse l nil");;
  _subreverse = Parse.define('subreverse', (function() {var f; return function _subreverse(){return f || (f = (function(_l){return function(_result){return _l()((function(){var $m; return (function(){return $m || ($m = (function(_h){return function(_t){return function(_D){return _subreverse()(_t)((function(){var $m; return (function(){return $m || ($m = (_cons()(_h)(_result)))})})());};};}))})})())(_result);};}));}})(), 2, "\\l result . l (\\h t D . subreverse t (cons h result)) result");;
  _if = Parse.define('if', (function _if() {return ((_id()));}), 0, "id");;
  _at = Parse.define('at', (function() {var f; return function _at(){return f || (f = (function(_l){return function(_x){return _iszero()(_x)((function(){var $m; return (function(){return $m || ($m = (_head()(_l)))})})())((function(){var $m; return (function(){return $m || ($m = (_at()((function(){var $m; return (function(){return $m || ($m = (_tail()(_l)))})})())((function(){var $m; return (function(){return $m || ($m = (_$_$_()(_x)))})})())))})})());};}));}})(), 2, "\\l x . (iszero (x)) (head l) (at (tail l) (-- (x) ) )");;
  _index_combine = Parse.define('index_combine', (function() {var f; return function _index_combine(){return f || (f = (function(_x){return function(_y){return _or()((function(){var $m; return (function(){return $m || ($m = (_eq()(_x)(_nil)))})})())((function(){var $m; return (function(){return $m || ($m = (_eq()(_y)(_nil)))})})())(_nil)((function(){var $m; return (function(){return $m || ($m = (_$o()(_x)(_y)))})})());};}));}})(), 2, "\\x y . (or (eq x nil) (eq y nil)) (nil) (+ x y)");;
  _indexof = Parse.define('indexof', (function() {var f; return function _indexof(){return f || (f = (function(_l){return function(_x){return _if()((function(){var $m; return (function(){return $m || ($m = (_eq()(_l)(_nil)))})})())(_nil)((function(){var $m; return (function(){return $m || ($m = (_if()((function(){var $m; return (function(){return $m || ($m = (_eq()(_x)((function(){var $m; return (function(){return $m || ($m = (_head()(_l)))})})())))})})())((function(){return 0}))((function(){var $m; return (function(){return $m || ($m = (_index_combine()((function(){return 1}))((function(){var $m; return (function(){return $m || ($m = (_indexof()((function(){var $m; return (function(){return $m || ($m = (_tail()(_l)))})})())(_x)))})})())))})})())))})})());};}));}})(), 2, "\\l x . if (eq l nil) (nil) (if (eq x (head l)) (0) (index_combine 1 (indexof (tail l) x ) ) )");;
  _position = Parse.define('position', (function() {var f; return function _position(){return f || (f = (function(_l){return function(_x){return _indexof()(_x)(_l);};}));}})(), 2, "\\l x . indexof x l");;
  _$r = Parse.defineMacro('[', (function() {var f; return function _$r(){return f || (f = (function(_list){return _constructList()((function(){var $m; return (function(){return $m || ($m = (_tail()(_list)))})})());}));}})(), 1, "\\list . constructList (tail list)");;
  _constructList = Parse.define('constructList', (function() {var f; return function _constructList(){return f || (f = (function(_list){return _cl()((function(){var $m; return (function(){return $m || ($m = (_head()(_list)))})})())((function(){var $m; return (function(){return $m || ($m = (_tokString()((function(){var $m; return (function(){return $m || ($m = (_head()(_list)))})})())))})})())((function(){var $m; return (function(){return $m || ($m = (_tail()(_list)))})})());}));}})(), 1, "\\list . cl (head list) (tokString (head list)) (tail list)");;
  _constructList = Leisure.makeDispatchFunction('constructList', '_constructList', '_list', ['_constructList', '_list']);
Leisure.createMethod('nil', 'constructList', "\\list      . nil", function(_list) {return _nil();});
  _cl = Parse.define('cl', (function() {var f; return function _cl(){return f || (f = (function(_h){return function(_hs){return function(_t){return _eq()(_hs)((function(){return "|"}))((function(){var $m; return (function(){return $m || ($m = (_eq()((function(){var $m; return (function(){return $m || ($m = (_length()(_t)))})})())((function(){return 2}))((function(){var $m; return (function(){return $m || ($m = (_cons()((function(){var $m; return (function(){return $m || ($m = (_head()(_t)))})})())(_nil)))})})())((function(){var $m; return (function(){return $m || ($m = (_error()((function(){return "Bad list format."}))))})})())))})})())((function(){var $m; return (function(){return $m || ($m = (_eq()(_hs)((function(){return "]"}))((function(){var $m; return (function(){return $m || ($m = (_cons()((function(){return "nil"}))(_nil)))})})())((function(){var $m; return (function(){return $m || ($m = (_eq()(_hs)((function(){return ","}))((function(){var $m; return (function(){return $m || ($m = (_constructList()(_t)))})})())((function(){var $m; return (function(){return $m || ($m = (_cons()((function(){var $m; return (function(){return $m || ($m = (_cons()((function(){return "cons"}))((function(){var $m; return (function(){return $m || ($m = (_cons()(_h)((function(){var $m; return (function(){return $m || ($m = (_constructList()(_t)))})})())))})})())))})})())(_nil)))})})())))})})())))})})());};};}));}})(), 3, "\\h hs t . eq hs '|'\n  eq (length t) 2\n    # -- scanner ensures: eq (tokString (head (tail t))) ']'\n    cons (head t) nil\n    error \"Bad list format.\"\n  eq hs ']'\n    # -- scanner ensures: eq t nil\n    cons 'nil' nil\n    eq hs ','\n      constructList t\n      cons (cons 'cons' (cons h (constructList t))) nil");;
  _tokString = Parse.define('tokString', (function() {var f; return function _tokString(){return f || (f = (function(_x){return _x();}));}})(), 1, "\\x . x");;
  _tokString = Leisure.makeDispatchFunction('tokString', '_tokString', '_t', ['_tokString', '_t']);
Leisure.createMethod('token', 'tokString', "\\t        . t \\t p . t", function(_t) {return _t()((function(){var $m; return (function(){return $m || ($m = (function(_t){return function(_p){return _t();};}))})})());});
  _identMacro = Parse.defineMacro('identMacro', (function() {var f; return function _identMacro(){return f || (f = (function(_list){return _tail()(_list);}));}})(), 1, "\\list . tail list");;
  _macroCons = Parse.defineMacro('macroCons', (function() {var f; return function _macroCons(){return f || (f = (function(_list){return _cons()((function(){return "cons"}))((function(){var $m; return (function(){return $m || ($m = (_tail()(_list)))})})());}));}})(), 1, "\\list . cons 'cons' (tail list)");;
  _concat$r = Parse.defineMacro('concat[', (function() {var f; return function _concat$r(){return f || (f = (function(_list){return _cons()((function(){var $m; return (function(){return $m || ($m = (_token()((function(){return "concat"}))((function(){var $m; return (function(){return $m || ($m = (_tokenStart()(_list)))})})())))})})())((function(){var $m; return (function(){return $m || ($m = (_cons()((function(){var $m; return (function(){return $m || ($m = (_cons()((function(){var $m; return (function(){return $m || ($m = (_token()((function(){return "["}))((function(){var $m; return (function(){return $m || ($m = (_tokenStart()((function(){var $m; return (function(){return $m || ($m = (_tail()(_list)))})})())))})})())))})})())((function(){var $m; return (function(){return $m || ($m = (_tail()(_list)))})})())))})})())(_nil)))})})());}));}})(), 1, "\\list . cons (token 'concat' (tokenStart list)) (cons (cons (token '[' (tokenStart (tail list))) (tail list)) nil)");;
  _doFilter = Parse.define('doFilter', (function() {var f; return function _doFilter(){return f || (f = (function(_parseDefs){return function(_list){return _transformDo()(_list);};}));}})(), 2, "\\parseDefs list . transformDo list");;
  _transformDo = Parse.define('transformDo', (function() {var f; return function _transformDo(){return f || (f = (function(_list){return _list();}));}})(), 1, "\\list . list");;
  _transformDo = Leisure.makeDispatchFunction('transformDo', '_transformDo', '_list', ['_transformDo', '_list']);
Leisure.createMethod('cons', 'transformDo', "\\list       . subDos list", function(_list) {return _subDos()(_list);});
  _transformDo = Leisure.makeDispatchFunction('transformDo', '_transformDo', '_list', ['_transformDo', '_list']);
Leisure.createMethod('lexCons', 'transformDo', "\\list          . subDos list", function(_list) {return _subDos()(_list);});
  _subDos = Parse.define('subDos', (function() {var f; return function _subDos(){return f || (f = (function(_list){return _eq()((function(){return "do"}))((function(){var $m; return (function(){return $m || ($m = (_tokString()((function(){var $m; return (function(){return $m || ($m = (_head()(_list)))})})())))})})())((function(){var $m; return (function(){return $m || ($m = (_foldr1()((function(){var $m; return (function(){return $m || ($m = (function(_el){return _doClause()(_el);}))})})())((function(){var $m; return (function(){return $m || ($m = (_subNextDos()((function(){var $m; return (function(){return $m || ($m = (_tail()(_list)))})})())))})})())))})})())((function(){var $m; return (function(){return $m || ($m = (_subNextDos()(_list)))})})());}));}})(), 1, "\\list . eq 'do' (tokString (head list))\n  foldr1 (\\el . doClause el) (subNextDos (tail list))\n  subNextDos list");;
  _subNextDos = Parse.define('subNextDos', (function() {var f; return function _subNextDos(){return f || (f = (function(_nonlist){return _nonlist();}));}})(), 1, "\\nonlist . nonlist");;
  _subNextDos = Leisure.makeDispatchFunction('subNextDos', '_subNextDos', '_list', ['_subNextDos', '_list']);
Leisure.createMethod('cons', 'subNextDos', "\\list       . listSubNextDos list", function(_list) {return _listSubNextDos()(_list);});
  _subNextDos = Leisure.makeDispatchFunction('subNextDos', '_subNextDos', '_list', ['_subNextDos', '_list']);
Leisure.createMethod('lexCons', 'subNextDos', "\\list          . listSubNextDos list", function(_list) {return _listSubNextDos()(_list);});
  _listSubNextDos = Parse.define('listSubNextDos', (function() {var f; return function _listSubNextDos(){return f || (f = (function(_list){return _eq()((function(){return "."}))((function(){var $m; return (function(){return $m || ($m = (_tokString()((function(){var $m; return (function(){return $m || ($m = (_head()(_list)))})})())))})})())((function(){var $m; return (function(){return $m || ($m = (_cons()((function(){var $m; return (function(){return $m || ($m = (_head()(_list)))})})())((function(){var $m; return (function(){return $m || ($m = (_transformDo()((function(){var $m; return (function(){return $m || ($m = (_tail()(_list)))})})())))})})())))})})())((function(){var $m; return (function(){return $m || ($m = (_cons()((function(){var $m; return (function(){return $m || ($m = (_transformDo()((function(){var $m; return (function(){return $m || ($m = (_head()(_list)))})})())))})})())((function(){var $m; return (function(){return $m || ($m = (_subNextDos()((function(){var $m; return (function(){return $m || ($m = (_tail()(_list)))})})())))})})())))})})());}));}})(), 1, "\\list . eq '.' (tokString (head list))\n  cons (head list) (transformDo (tail list))\n  cons (transformDo (head list)) (subNextDos (tail list))");;
  _doClause = Parse.define('doClause', (function() {var f; return function _doClause(){return f || (f = (function(_clause){return function(_rest){return _doExtractVar()(_clause)((function(){return "<-"}))((function(){var $m; return (function(){return $m || ($m = (function(_var){return _cons()((function(){return "bind"}))((function(){var $m; return (function(){return $m || ($m = (_cons()((function(){var $m; return (function(){return $m || ($m = (_tail()((function(){var $m; return (function(){return $m || ($m = (_tail()(_clause)))})})())))})})())((function(){var $m; return (function(){return $m || ($m = (_cons()((function(){return "\\"}))((function(){var $m; return (function(){return $m || ($m = (_cons()(_var)((function(){var $m; return (function(){return $m || ($m = (_cons()((function(){return "."}))((function(){var $m; return (function(){return $m || ($m = (_cons()(_rest)(_nil)))})})())))})})())))})})())))})})())))})})());}))})})())((function(){var $m; return (function(){return $m || ($m = (_doExtractVar()(_clause)((function(){return "="}))((function(){var $m; return (function(){return $m || ($m = (function(_var){return _cons()((function(){var $m; return (function(){return $m || ($m = (_cons()((function(){return "\\"}))((function(){var $m; return (function(){return $m || ($m = (_cons()(_var)((function(){var $m; return (function(){return $m || ($m = (_cons()((function(){return "."}))((function(){var $m; return (function(){return $m || ($m = (_cons()(_rest)(_nil)))})})())))})})())))})})())))})})())((function(){var $m; return (function(){return $m || ($m = (_cons()((function(){var $m; return (function(){return $m || ($m = (_tail()((function(){var $m; return (function(){return $m || ($m = (_tail()(_clause)))})})())))})})())(_nil)))})})());}))})})())((function(){var $m; return (function(){return $m || ($m = (_cons()((function(){return "bind"}))((function(){var $m; return (function(){return $m || ($m = (_cons()(_clause)((function(){var $m; return (function(){return $m || ($m = (_cons()((function(){return "\\"}))((function(){var $m; return (function(){return $m || ($m = (_cons()((function(){return "_"}))((function(){var $m; return (function(){return $m || ($m = (_cons()((function(){return "."}))((function(){var $m; return (function(){return $m || ($m = (_cons()(_rest)(_nil)))})})())))})})())))})})())))})})())))})})())))})})())))})})());};}));}})(), 2, "\\clause rest . doExtractVar clause '<-'\n  \\var . cons 'bind' (cons (tail (tail clause)) (cons '\\\\' (cons var (cons '.' (cons rest nil)))))\n  doExtractVar clause '='\n    \\var . cons (cons '\\\\' (cons var (cons '.' (cons rest nil)))) (cons (tail (tail clause)) nil)\n    cons 'bind' (cons clause (cons '\\\\' (cons '_' (cons '.' (cons rest nil)))))");;
  _doExtractVar = Parse.define('doExtractVar', (function() {var f; return function _doExtractVar(){return f || (f = (function(_list){return function(_tokName){return _none();};}));}})(), 2, "\\list tokName . none");;
  _doExtractVar = Leisure.makeDispatchFunction('doExtractVar', '_doExtractVar', '_list', ['_doExtractVar', '_list', '_tokName']);
Leisure.createMethod('cons', 'doExtractVar', "\\list       tokName . listDoExtractVar list tokName", function(_list, _tokName) {return _listDoExtractVar()(_list)(_tokName);});
  _doExtractVar = Leisure.makeDispatchFunction('doExtractVar', '_doExtractVar', '_list', ['_doExtractVar', '_list', '_tokName']);
Leisure.createMethod('lexCons', 'doExtractVar', "\\list          tokName . listDoExtractVar list tokName", function(_list, _tokName) {return _listDoExtractVar()(_list)(_tokName);});
  _listDoExtractVar = Parse.define('listDoExtractVar', (function() {var f; return function _listDoExtractVar(){return f || (f = (function(_list){return function(_tokName){return _or()((function(){var $m; return (function(){return $m || ($m = (_null$e()((function(){var $m; return (function(){return $m || ($m = (_tail()(_list)))})})())))})})())((function(){var $m; return (function(){return $m || ($m = (_neq()(_tokName)((function(){var $m; return (function(){return $m || ($m = (_tokString()((function(){var $m; return (function(){return $m || ($m = (_head()((function(){var $m; return (function(){return $m || ($m = (_tail()(_list)))})})())))})})())))})})())))})})())(_none)((function(){var $m; return (function(){return $m || ($m = (_some()((function(){var $m; return (function(){return $m || ($m = (_head()(_list)))})})())))})})());};}));}})(), 2, "\\list tokName . or (null? (tail list)) (neq tokName (tokString (head (tail list))))\n  none\n  some (head list)");;

});
if (typeof window != 'undefined') Prim.runMonad(module.exports, Prim.defaultEnv, function(){});
}).call(this)