#!/bin/sh
STACK=3000
#STACK=4000
#STACK=10000
NODE=node

if [ "$1" == -D ]; then
    NODE=node-debug
    shift
fi

if [ -n "$(expr "$(uname -s)" : '\(CYGWIN\|WIN\)')" ]; then
    dir=$(dirname $(cygpath -a -d $0))
    build=$dir/../build
    inst=$dir/packages/leisure/build
    export NODE_PATH="$build;$build/node_modules"
    echo NODE_PATH="'$NODE_PATH'"
    echo $NODE --stack-size=$STACK $inst/src/runRepl "$@"
    $NODE --stack-size=$STACK $inst/src/runRepl "$@"
else
    dir=$(dirname $0)
    inst=$dir/packages/leisure/build
    export NODE_PATH="$dir/lib:$dir/client:$inst/lib:$dir/packages/org:$inst/src:$inst/node_modules"
    $NODE --stack-size=$STACK $inst/src/runRepl "$@"
fi
