#!/bin/sh
if [ -n "$(expr '$(uname -s)' : 'CYGWIN.*\|WIN.*')" ]; then
    dir=$(dirname $(cygpath -a -d $0))
    inst=$dir\\packages\\leisure\\build
    export NODE_PATH="$inst\\lib;$inst\\node_modules"
    node --stack-size=3000 $inst\\src\\runRepl "$@"
else
    dir=$(dirname $0)
    inst=$dir/packages/leisure/build
    export NODE_PATH="$inst/lib:$inst/node_modules"
    node --stack-size=3000 $inst/src/runRepl "$@"
fi
