#!/bin/sh
STACK=3000
#STACK=4000
#STACK=10000
NODE=node

if [ -n "$(expr "$(uname -s)" : '\(CYGWIN\|WIN\)')" ]; then
    dir=$(dirname $(cygpath -a -d $0))
    inst=$dir\\packages\\leisure\\build
    export NODE_PATH="$dir\\lib;$dir\\client;$inst\\lib;$dir\\packages\\org;$inst\\src;$inst\\node_modules"
    echo $NODE --stack-size=$STACK $inst\\src\\runRepl "$@"
    $NODE --stack-size=$STACK $inst\\src\\runRepl "$@"
else
    dir=$(dirname $0)
    inst=$dir/packages/leisure/build
    export NODE_PATH="$dir/lib:$dir/client:$inst/lib:$dir/packages/org:$inst/src:$inst/node_modules"
    $NODE --stack-size=$STACK $inst/src/runRepl "$@"
fi
