#!/bin/sh

LEISURE_BASE=$(dirname $(dirname $(readlink -f $0)))

if [ -n "$NODE_PATH" ]; then
    export NODE_PATH="$NODE_PATH:$LEISURE_BASE"
else
    export NODE_PATH="$LEISURE_BASE"
fi
exec node --stack-size=3000 --debug "$LEISURE_BASE/lib/repl" "$@"
