// Generated by CoffeeScript 1.7.1
(function() {
  Leisure.require = require;

  require('persistent-hash-trie');

  require('./lodash.min');

  require('source-map');

  require('./org');

  require('./github');

  require('./base64');

  require('./diff');

  require('./sha256');

  require('utf8');

  require('js-yaml');

}).call(this);

//# sourceMappingURL=browserMain.map
