// Generated by CoffeeScript 1.6.3
(function() {
  var k, v, _ref;

  Leisure.require = require;

  require('persistent-hash-trie');

  require('./lodash.min');

  require('source-map');

  window.org = require('./org');

  _ref = window.Leisure;
  for (k in _ref) {
    v = _ref[k];
    Leisure[k] = v;
  }

  window.Leisure = Leisure;

}).call(this);

/*
//@ sourceMappingURL=browserMain.map
*/
