// Generated by CoffeeScript 1.6.2
/*
Copyright (C) 2013, Bill Burdick

(licensed with ZLIB license)

This software is provided 'as-is', without any express or implied
warranty. In no event will the authors be held liable for any damages
arising from the use of this software.

Permission is granted to anyone to use this software for any purpose,
including commercial applications, and to alter it and redistribute it
freely, subject to the following restrictions:

1. The origin of this software must not be misrepresented; you must not
claim that you wrote the original software. If you use this software
in a product, an acknowledgment in the product documentation would be
appreciated but is not required.

2. Altered source versions must be plainly marked as such, and must not be
misrepresented as being the original software.

3. This notice may not be removed or altered from any source distribution.
*/


(function() {
  var deferUntilStart, displayResults, modules, showTraces, startFuncs, started, tests;

  tests = function() {
    return window.Tests;
  };

  window.global = window;

  window.module = {};

  window.Tests = {
    readFile: function(filename, cont) {
      return window.setTimeout((function() {
        return $.get(filename, function(data) {
          return cont(false, data);
        });
      }), 1);
    }
  };

  window.require = function(name) {
    return modules[name]();
  };

  window.process = {
    exit: function() {},
    stdout: {
      write: function(s) {
        return console.log(s);
      }
    }
  };

  modules = {
    './lodash.min': function() {
      return window._;
    },
    './base': tests,
    './ast': tests,
    './base': tests,
    './gen': tests,
    './runtime': tests,
    './simpleParse': tests,
    './testing': function() {
      var oldRunTests;

      console.log("Accessing ./testing");
      oldRunTests = window.Tests.runTests;
      window.Tests.runTests = function(tests) {
        oldRunTests(tests);
        return displayResults();
      };
      return window.Tests;
    },
    './testLeisure': tests
  };

  startFuncs = [];

  started = false;

  window.Tests.loaded = function() {
    var func;

    console.log('body loaded');
    return window.setTimeout(((function() {
      var _i, _len;

      (function() {});
      if (!started) {
        started = true;
        for (_i = 0, _len = startFuncs.length; _i < _len; _i++) {
          func = startFuncs[_i];
          func();
        }
        return startFuncs = null;
      }
    })()), 1);
  };

  document.addEventListener('load', function() {
    return console.log('document loaded');
  });

  deferUntilStart = function(func) {
    if (started) {
      return func();
    } else {
      return startFuncs.push(func);
    }
  };

  displayResults = function() {
    return window.setTimeout((function() {
      var results, stats;

      results = document.getElementById('results');
      if (results) {
        stats = window.Tests.stats;
        if (stats.failures) {
          results.classList.remove('succeeded');
          results.classList.add('failed');
          if (stats.successes) {
            results.innerHTML = "Succeeded: <b>" + stats.successes + "</b><br>Failed: <b>" + stats.failures;
          } else {
            results.innerHTML = "Succeeded: <b>None</b><br>Failed: <b>" + stats.failures;
          }
          return showTraces();
        } else {
          results.classList.add('succeeded');
          results.classList.remove('failed');
          if (stats.failures) {
            return results.innerHTML = "Succeeded: <b>" + stats.successes + "</b><br>Failed: <b>" + stats.failures;
          } else {
            return results.innerHTML = "Succeeded: <b>" + stats.successes + "</b><br>Failed: <b>None</b>";
          }
        }
      }
    }), 1);
  };

  showTraces = function() {
    var stats, trace, traceDiv, _i, _len, _ref, _results;

    stats = window.Tests.stats;
    traceDiv = document.getElementById('traces');
    traceDiv.innerHTML = '';
    _ref = stats.traces;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      trace = _ref[_i];
      _results.push(traceDiv.innerHTML += "<div>" + trace + "</div><br>");
    }
    return _results;
  };

}).call(this);

/*
//@ sourceMappingURL=browser.map
*/
