// Generated by CoffeeScript 1.6.3
(function() {
  Leisure.require = require;

  require('persistent-hash-trie');

  require('./lodash.min');

  require('source-map');

  require('./org');

  require('./github');

}).call(this);

/*
//@ sourceMappingURL=browserMain.map
*/
