// Generated by CoffeeScript 1.7.1
(function() {
  var createInfoDivs, createNode, defaultEnv, enterButtonInfo, enterRowInfo, infos, lazy, lz, menuInfo, numberKeysInfo, resolve, root, rz, setInput, topInfo, useSkin, _ref;

  _ref = root = module.exports = require('./base'), resolve = _ref.resolve, lazy = _ref.lazy, defaultEnv = _ref.defaultEnv;

  rz = resolve;

  lz = lazy;

  createNode = require('./browserSupport').createNode;

  menuInfo = {
    "class": 'mode',
    width: 74,
    height: 46,
    tops: [364],
    lefts: [23, 143, 263, 383, 503, 623]
  };

  topInfo = {
    "class": 'function',
    width: 74,
    height: 58,
    tops: [444, 545, 647],
    lefts: [23, 143, 263, 383, 503, 623]
  };

  enterButtonInfo = {
    "class": 'enterButton',
    width: 194,
    height: 58,
    tops: [748],
    lefts: [23]
  };

  enterRowInfo = {
    "class": 'enterRow',
    width: 74,
    height: 58,
    tops: [748],
    lefts: [263, 383, 503, 623]
  };

  numberKeysInfo = {
    "class": 'numbers',
    width: 98,
    height: 59,
    tops: [850, 952, 1053, 1155],
    lefts: [23, 167, 311, 455, 599]
  };

  infos = [menuInfo, topInfo, enterButtonInfo, enterRowInfo, numberKeysInfo];

  useSkin = function() {
    var info, _i, _len;
    $('body').addClass('calcMain');
    $(document.head).append("<link href='calcSkin.css' rel='stylesheet' type='text/css'>");
    for (_i = 0, _len = infos.length; _i < _len; _i++) {
      info = infos[_i];
      createInfoDivs(info);
    }
    setInput(numberKeysInfo, 0, 3, 1);
    setInput(numberKeysInfo, 1, 2, 1);
    setInput(numberKeysInfo, 2, 2, 2);
    setInput(numberKeysInfo, 3, 2, 3);
    setInput(numberKeysInfo, 4, 1, 1);
    setInput(numberKeysInfo, 5, 1, 2);
    setInput(numberKeysInfo, 6, 1, 3);
    setInput(numberKeysInfo, 7, 0, 1);
    setInput(numberKeysInfo, 8, 0, 2);
    setInput(numberKeysInfo, 9, 0, 3);
    setInput(numberKeysInfo, '/', 0, 4);
    setInput(numberKeysInfo, '*', 1, 4);
    setInput(numberKeysInfo, '-', 2, 4);
    setInput(numberKeysInfo, '+', 3, 4);
    setInput(numberKeysInfo, '.', 3, 2);
    setInput(numberKeysInfo, ' ', 3, 3);
    enterRowInfo.divs[0][3].mousedown(function(evt) {
      document.execCommand('insertText', false, String(input));
      return evt.preventDefault();
    });
    menuInfo.divs[0][0].mousedown(function(evt) {
      evt.preventDefault();
      $('#simplifiedPanel').addClass('hidden');
      return $('#astPanel').toggleClass('hidden');
    });
    return menuInfo.divs[0][1].mousedown(function(evt) {
      evt.preventDefault();
      $('#astPanel').addClass('hidden');
      return $('#simplifiedPanel').toggleClass('hidden');
    });
  };

  setInput = function(info, input, top, left) {
    return info.divs[top][left].mousedown(function(evt) {
      document.execCommand('insertText', false, String(input));
      return evt.preventDefault();
    });
  };

  createInfoDivs = function(info) {
    var div, left, top;
    return info.divs = (function() {
      var _i, _ref1, _results;
      _results = [];
      for (top = _i = 0, _ref1 = info.tops.length; 0 <= _ref1 ? _i < _ref1 : _i > _ref1; top = 0 <= _ref1 ? ++_i : --_i) {
        _results.push((function() {
          var _j, _ref2, _results1;
          _results1 = [];
          for (left = _j = 0, _ref2 = info.lefts.length; 0 <= _ref2 ? _j < _ref2 : _j > _ref2; left = 0 <= _ref2 ? ++_j : --_j) {
            div = $(document.createElement('DIV'));
            div.addClass('calcButton').addClass(info["class"]).addClass("top" + top).addClass("left" + left);
            $('#calc').append(div);
            _results1.push(div);
          }
          return _results1;
        })());
      }
      return _results;
    })();
  };

  root.useSkin = useSkin;

}).call(this);

//# sourceMappingURL=calcSkin.map
