// Generated by CoffeeScript 1.6.2
(function() {
  var defaultEnv, fs, root;

  defaultEnv = (root = module.exports = require('./base')).defaultEnv;

  fs = require('fs');

  defaultEnv.readFile = function(fileName, cont) {
    return fs.readFile(fileName, {
      encoding: 'utf8'
    }, cont);
  };

  defaultEnv.writeFile = function(fileName, data, cont) {
    return fs.writeFile(fileName, data, {
      encoding: 'utf8'
    }, cont);
  };

}).call(this);

/*
//@ sourceMappingURL=node.map
*/
