// Generated by CoffeeScript 1.7.1
(function() {
  var arg, dir, root;

  root = module.exports = require('./base');

  require('./server');

  arg = 0;

  dir = 'www';

  while (arg < process.argv.length) {
    switch (process.argv[arg]) {
      case '-d':
        dir = process.argv[++arg];
    }
    arg++;
  }

  root.createServer({
    dir: dir
  });

}).call(this);

//# sourceMappingURL=startServer.map
