L_runMonads([
  function(){return resolve(L_define)(function(){return "if"})(function(){return 0})(function(){return "if = id"})(L_id)},
  function(){return resolve(L_define)(function(){return "afetch"})(function(){return 2})(function(){return "afetch k alist  = alist (\\h t D . h \\key value . eq key k value (afetch k t)) nil"})((function(){var $m; return function(){return $m || ($m = function(L_k){return function(L_alist){return resolve(L_alist)((function(){var $m; return function(){return $m || ($m = function(L_h){return function(L_t){return function(L_D){return resolve(L_h)((function(){var $m; return function(){return $m || ($m = function(L_key){return function(L_value){return resolve(L_eq)(L_key)(L_k)(L_value)((function(){var $m; return function(){return $m || ($m = resolve(L_afetch)(L_k)(L_t))}})())}})}})())}}})}})())(L_nil)}})}})())},
  function(){return resolve(L_define)(function(){return "aconsf"})(function(){return 3})(function(){return "aconsf key value list = acons key value (aremove key list)"})((function(){var $m; return function(){return $m || ($m = function(L_key){return function(L_value){return function(L_list){return resolve(L_acons)(L_key)(L_value)((function(){var $m; return function(){return $m || ($m = resolve(L_aremove)(L_key)(L_list))}})())}}})}})())},
  function(){return resolve(L_define)(function(){return "aremove"})(function(){return 2})(function(){return "aremove key list = isNil list\n  nil\n  eq (head (head list)) key\n    aremove key (tail list)\n    aconsPair (head list) (aremove key (tail list))"})((function(){var $m; return function(){return $m || ($m = function(L_key){return function(L_list){return resolve(L_isNil)(L_list)(L_nil)((function(){var $m; return function(){return $m || ($m = resolve(L_eq)((function(){var $m; return function(){return $m || ($m = resolve(L_head)((function(){var $m; return function(){return $m || ($m = resolve(L_head)(L_list))}})()))}})())(L_key)((function(){var $m; return function(){return $m || ($m = resolve(L_aremove)(L_key)((function(){var $m; return function(){return $m || ($m = resolve(L_tail)(L_list))}})()))}})())((function(){var $m; return function(){return $m || ($m = resolve(L_aconsPair)((function(){var $m; return function(){return $m || ($m = resolve(L_head)(L_list))}})())((function(){var $m; return function(){return $m || ($m = resolve(L_aremove)(L_key)((function(){var $m; return function(){return $m || ($m = resolve(L_tail)(L_list))}})()))}})()))}})()))}})())}})}})())},
  function(){return resolve(L_defMacro)(function(){return "when"})((function(){var $m; return function(){return $m || ($m = function(L_line){return resolve(L_line)((function(){var $m; return function(){return $m || ($m = function(L_cond){return function(L_rest){return resolve(L_cons)(L_cond)((function(){var $m; return function(){return $m || ($m = resolve(L_cons)((function(){var $m; return function(){return $m || ($m = resolve(L_cons)(function(){return "do"})(L_rest))}})())((function(){var $m; return function(){return $m || ($m = resolve(L_cons)(function(){return "nil"})(L_nil))}})()))}})())}})}})())})}})())},
  function(){return resolve(L_addTokenGroup)(function(){return "js["})(function(){return "]"})},
  function(){return resolve(L_defMacro)(function(){return "js["})((function(){var $m; return function(){return $m || ($m = function(L_list){return resolve(L_cons)(function(){return "js"})((function(){var $m; return function(){return $m || ($m = resolve(L_cons)((function(){var $m; return function(){return $m || ($m = resolve(L_cons)(function(){return "strCat"})((function(){var $m; return function(){return $m || ($m = resolve(L_cons)((function(){var $m; return function(){return $m || ($m = resolve(L_cons)(function(){return "flatten"})((function(){var $m; return function(){return $m || ($m = resolve(L_cons)((function(){var $m; return function(){return $m || ($m = resolve(L_cons)((function(){var $m; return function(){return $m || ($m = resolve(L_listify)((function(){var $m; return function(){return $m || ($m = resolve(L_head)(L_list))}})()))}})())(L_nil))}})())(L_nil))}})()))}})())(L_nil))}})()))}})())(L_nil))}})())})}})())},
  function(){return resolve(L_define)(function(){return "html"})(function(){return 1})(function(){return "html x = \\f . f x"})((function(){var $m; return function(){return $m || ($m = setDataType(function(L_x){return setType(function(L_f){return resolve(L_f)(L_x)}, 'html')}, 'html'))}})())},
  function(){return resolve(L_define)(function(){return "iszero"})(function(){return 0})(function(){return "iszero = eq 0"})((function(){var $m; return function(){return $m || ($m = resolve(L_eq)(function(){return 0}))}})())},
  function(){return resolve(L_define)(function(){return "positive"})(function(){return 0})(function(){return "positive = 0 <"})((function(){var $m; return function(){return $m || ($m = resolve(L_$y)(function(){return 0}))}})())},
  function(){return resolve(L_addToken)(function(){return "--"})},
  function(){return resolve(L_addToken)(function(){return "++"})},
  function(){return resolve(L_define)(function(){return "--"})(function(){return 0})(function(){return "-- = (flip (-)) 1"})((function(){var $m; return function(){return $m || ($m = resolve(L_flip)(L_$_)(function(){return 1}))}})())},
  function(){return resolve(L_define)(function(){return "++"})(function(){return 0})(function(){return "++ = (1 +)"})((function(){var $m; return function(){return $m || ($m = resolve(L_$o)(function(){return 1}))}})())},
  function(){return resolve(L_define)(function(){return "intercalate"})(function(){return 2})(function(){return "intercalate x l = concat (intersperse x l)"})((function(){var $m; return function(){return $m || ($m = function(L_x){return function(L_l){return resolve(L_concat)((function(){var $m; return function(){return $m || ($m = resolve(L_intersperse)(L_x)(L_l))}})())}})}})())},
  function(){return resolve(L_define)(function(){return "visit"})(function(){return 2})(function(){return "visit func l = \\\\\n  result = func func l\n  .\n  isCons result\n    result \\h t . cons (visit func h) (visit func t)\n    result"})((function(){var $m; return function(){return $m || ($m = function(L_func){return function(L_l){return (function(){

var L_result;

L_result = (function(){var $m; return function(){return $m || ($m = resolve(L_func)(L_func)(L_l))}})();
return resolve(L_isCons)(L_result)((function(){var $m; return function(){return $m || ($m = resolve(L_result)((function(){var $m; return function(){return $m || ($m = function(L_h){return function(L_t){return resolve(L_cons)((function(){var $m; return function(){return $m || ($m = resolve(L_visit)(L_func)(L_h))}})())((function(){var $m; return function(){return $m || ($m = resolve(L_visit)(L_func)(L_t))}})())}})}})()))}})())(L_result)})()}})}})())},
  function(){return resolve(L_define)(function(){return "simplify"})(function(){return 1})(function(){return "simplify exprString = do\n  list <- scanLineM exprString\n  visit (\\func x . isToken x (tokenString x) ((isParens x) (visit func (parensContent x)) x)) list"})((function(){var $m; return function(){return $m || ($m = function(L_exprString){return resolve(L_bind)((function(){var $m; return function(){return $m || ($m = resolve(L_scanLineM)(L_exprString))}})())((function(){var $m; return function(){return $m || ($m = function(L_list){return resolve(L_visit)((function(){var $m; return function(){return $m || ($m = function(L_func){return function(L_x){return resolve(L_isToken)(L_x)((function(){var $m; return function(){return $m || ($m = resolve(L_tokenString)(L_x))}})())((function(){var $m; return function(){return $m || ($m = resolve(L_isParens)(L_x)((function(){var $m; return function(){return $m || ($m = resolve(L_visit)(L_func)((function(){var $m; return function(){return $m || ($m = resolve(L_parensContent)(L_x))}})()))}})())(L_x))}})())}})}})())(L_list)})}})())})}})())},
  function(){return resolve(L_define)(function(){return "doall"})(function(){return 0})(function(){return "doall = foldr1 (\\el res . bind el \\_ . res)"})((function(){var $m; return function(){return $m || ($m = resolve(L_foldr1)((function(){var $m; return function(){return $m || ($m = function(L_el){return function(L_res){return resolve(L_bind)(L_el)((function(){var $m; return function(){return $m || ($m = function(L__){return resolve(L_res)})}})())}})}})()))}})())},
  function(){return resolve(L_define)(function(){return "requireJS"})(function(){return 1})(function(){return "requireJS file = bind (getValue 'requiredFiles')\n  \\files . contains files file\n    false\n    bind (loadJS file)\n      \\result . result\n        \\x . left x\n        \\_ . bind (setValue 'requiredFiles' (cons file files))\n          \\_ . right true"})((function(){var $m; return function(){return $m || ($m = function(L_file){return resolve(L_bind)((function(){var $m; return function(){return $m || ($m = resolve(L_getValue)(function(){return "requiredFiles"}))}})())((function(){var $m; return function(){return $m || ($m = function(L_files){return resolve(L_contains)(L_files)(L_file)(L_false)((function(){var $m; return function(){return $m || ($m = resolve(L_bind)((function(){var $m; return function(){return $m || ($m = resolve(L_loadJS)(L_file))}})())((function(){var $m; return function(){return $m || ($m = function(L_result){return resolve(L_result)((function(){var $m; return function(){return $m || ($m = function(L_x){return resolve(L_left)(L_x)})}})())((function(){var $m; return function(){return $m || ($m = function(L__){return resolve(L_bind)((function(){var $m; return function(){return $m || ($m = resolve(L_setValue)(function(){return "requiredFiles"})((function(){var $m; return function(){return $m || ($m = resolve(L_cons)(L_file)(L_files))}})()))}})())((function(){var $m; return function(){return $m || ($m = function(L___0){return resolve(L_right)(L_true)})}})())})}})())})}})()))}})())})}})())})}})())},
  function(){return resolve(L_define)(function(){return "loadJS"})(function(){return 1})(function(){return "loadJS file = bind (readFile file)\n  \\result . result\n    \\err . err\n    \\contents . js contents"})((function(){var $m; return function(){return $m || ($m = function(L_file){return resolve(L_bind)((function(){var $m; return function(){return $m || ($m = resolve(L_readFile)(L_file))}})())((function(){var $m; return function(){return $m || ($m = function(L_result){return resolve(L_result)((function(){var $m; return function(){return $m || ($m = function(L_err){return resolve(L_err)})}})())((function(){var $m; return function(){return $m || ($m = function(L_contents){return resolve(L_js)(L_contents)})}})())})}})())})}})())},
  function(){return resolve(L_define)(function(){return "findOption"})(function(){return 2})(function(){return "findOption func list = do\n  result = func (head list)\n  isNil list\n    none\n    isNone result\n      findOption func (tail list)\n      result"})((function(){var $m; return function(){return $m || ($m = function(L_func){return function(L_list){return (function(){

var L_result;

L_result = (function(){var $m; return function(){return $m || ($m = resolve(L_func)((function(){var $m; return function(){return $m || ($m = resolve(L_head)(L_list))}})()))}})();
return resolve(L_isNil)(L_list)(L_none)((function(){var $m; return function(){return $m || ($m = resolve(L_isNone)(L_result)((function(){var $m; return function(){return $m || ($m = resolve(L_findOption)(L_func)((function(){var $m; return function(){return $m || ($m = resolve(L_tail)(L_list))}})()))}})())(L_result))}})())})()}})}})())},
  function(){return resolve(L_define)(function(){return "dlempty"})(function(){return 0})(function(){return "dlempty = id"})(L_id)},
  function(){return resolve(L_define)(function(){return "dl"})(function(){return 1})(function(){return "dl item = \\rest . item:rest"})((function(){var $m; return function(){return $m || ($m = setDataType(function(L_item){return setType(function(L_rest){return resolve(L_cons)(L_item)(L_rest)}, 'dl')}, 'dl'))}})())},
  function(){return resolve(L_define)(function(){return "dlPush"})(function(){return 2})(function(){return "dlPush list item = dlAppend list (dl item)"})((function(){var $m; return function(){return $m || ($m = function(L_list){return function(L_item){return resolve(L_dlAppend)(L_list)((function(){var $m; return function(){return $m || ($m = resolve(L_dl)(L_item))}})())}})}})())},
  function(){return resolve(L_define)(function(){return "dlAppend"})(function(){return 2})(function(){return "dlAppend a b = \\rest . a (b rest)"})((function(){var $m; return function(){return $m || ($m = setDataType(function(L_a){return function(L_b){return setType(function(L_rest){return resolve(L_a)((function(){var $m; return function(){return $m || ($m = resolve(L_b)(L_rest))}})())}, 'dlAppend')}}, 'dlAppend'))}})())},
  function(){return resolve(L_define)(function(){return "remove"})(function(){return 2})(function(){return "remove x l = removeIf (eq x) l"})((function(){var $m; return function(){return $m || ($m = function(L_x){return function(L_l){return resolve(L_removeIf)((function(){var $m; return function(){return $m || ($m = resolve(L_eq)(L_x))}})())(L_l)}})}})())},
  function(){return resolve(L_define)(function(){return "removeIf"})(function(){return 2})(function(){return "removeIf f l = filter (compose not f) l"})((function(){var $m; return function(){return $m || ($m = function(L_f){return function(L_l){return resolve(L_filter)((function(){var $m; return function(){return $m || ($m = resolve(L_compose)(L_not)(L_f))}})())(L_l)}})}})())},
  function(){return resolve(L_define)(function(){return "any"})(function(){return 2})(function(){return "any f l = find f l (\\el . true) false"})((function(){var $m; return function(){return $m || ($m = function(L_f){return function(L_l){return resolve(L_find)(L_f)(L_l)((function(){var $m; return function(){return $m || ($m = function(L_el){return resolve(L_true)})}})())(L_false)}})}})())},
  function(){return resolve(L_define)(function(){return "all"})(function(){return 2})(function(){return "all f l = not any (compose not f) l"})((function(){var $m; return function(){return $m || ($m = function(L_f){return function(L_l){return resolve(L_not)(L_any)((function(){var $m; return function(){return $m || ($m = resolve(L_compose)(L_not)(L_f))}})())(L_l)}})}})())},
  function(){return resolve(L_define)(function(){return "take"})(function(){return 2})(function(){return "take n list = positive n\n  list\n    \\h t D . cons h (take (-- n) t)\n    nil\n  nil"})((function(){var $m; return function(){return $m || ($m = function(L_n){return function(L_list){return resolve(L_positive)(L_n)((function(){var $m; return function(){return $m || ($m = resolve(L_list)((function(){var $m; return function(){return $m || ($m = function(L_h){return function(L_t){return function(L_D){return resolve(L_cons)(L_h)((function(){var $m; return function(){return $m || ($m = resolve(L_take)((function(){var $m; return function(){return $m || ($m = resolve(L_$_$_)(L_n))}})())(L_t))}})())}}})}})())(L_nil))}})())(L_nil)}})}})())},
  function(){return resolve(L_define)(function(){return "takeWhile"})(function(){return 2})(function(){return "takeWhile predicate list = list\n  \\h t D . predicate (head list)\n    cons h (takeWhile predicate t)\n    nil\n  nil"})((function(){var $m; return function(){return $m || ($m = function(L_predicate){return function(L_list){return resolve(L_list)((function(){var $m; return function(){return $m || ($m = function(L_h){return function(L_t){return function(L_D){return resolve(L_predicate)((function(){var $m; return function(){return $m || ($m = resolve(L_head)(L_list))}})())((function(){var $m; return function(){return $m || ($m = resolve(L_cons)(L_h)((function(){var $m; return function(){return $m || ($m = resolve(L_takeWhile)(L_predicate)(L_t))}})()))}})())(L_nil)}}})}})())(L_nil)}})}})())},
  function(){return resolve(L_define)(function(){return "drop"})(function(){return 2})(function(){return "drop x list = positive x\n  list\n    \\h t D . drop (-- x) t\n    nil\n  list"})((function(){var $m; return function(){return $m || ($m = function(L_x){return function(L_list){return resolve(L_positive)(L_x)((function(){var $m; return function(){return $m || ($m = resolve(L_list)((function(){var $m; return function(){return $m || ($m = function(L_h){return function(L_t){return function(L_D){return resolve(L_drop)((function(){var $m; return function(){return $m || ($m = resolve(L_$_$_)(L_x))}})())(L_t)}}})}})())(L_nil))}})())(L_list)}})}})())},
  function(){return resolve(L_define)(function(){return "dropWhile"})(function(){return 2})(function(){return "dropWhile predicate list = list\n  \\h t D . predicate h\n    dropWhile predicate t\n    list\n  nil"})((function(){var $m; return function(){return $m || ($m = function(L_predicate){return function(L_list){return resolve(L_list)((function(){var $m; return function(){return $m || ($m = function(L_h){return function(L_t){return function(L_D){return resolve(L_predicate)(L_h)((function(){var $m; return function(){return $m || ($m = resolve(L_dropWhile)(L_predicate)(L_t))}})())(L_list)}}})}})())(L_nil)}})}})())},
  function(){return resolve(L_define)(function(){return "dropLast"})(function(){return 2})(function(){return "dropLast n list = reverse (drop n (reverse list))"})((function(){var $m; return function(){return $m || ($m = function(L_n){return function(L_list){return resolve(L_reverse)((function(){var $m; return function(){return $m || ($m = resolve(L_drop)(L_n)((function(){var $m; return function(){return $m || ($m = resolve(L_reverse)(L_list))}})()))}})())}})}})())},
  function(){return resolve(L_define)(function(){return "box"})(function(){return 2})(function(){return "box n list = list == nil\n  nil\n  [(take n list) | box n (drop n list)]"})((function(){var $m; return function(){return $m || ($m = function(L_n){return function(L_list){return resolve(L_$p$p)(L_list)(L_nil)(L_nil)((function(){var $m; return function(){return $m || ($m = resolve(L_cons)((function(){var $m; return function(){return $m || ($m = resolve(L_take)(L_n)(L_list))}})())((function(){var $m; return function(){return $m || ($m = resolve(L_box)(L_n)((function(){var $m; return function(){return $m || ($m = resolve(L_drop)(L_n)(L_list))}})()))}})()))}})())}})}})())},
  function(){return resolve(L_define)(function(){return "at"})(function(){return 2})(function(){return "at l x = (x == 0) (head l) (at (tail l) (-- (x) ) )"})((function(){var $m; return function(){return $m || ($m = function(L_l){return function(L_x){return resolve(L_$p$p)(L_x)(function(){return 0})((function(){var $m; return function(){return $m || ($m = resolve(L_head)(L_l))}})())((function(){var $m; return function(){return $m || ($m = resolve(L_at)((function(){var $m; return function(){return $m || ($m = resolve(L_tail)(L_l))}})())((function(){var $m; return function(){return $m || ($m = resolve(L_$_$_)(L_x))}})()))}})())}})}})())},
  function(){return resolve(L_define)(function(){return "series"})(function(){return 2})(function(){return "series func n = n:(series func (func n))"})((function(){var $m; return function(){return $m || ($m = function(L_func){return function(L_n){return resolve(L_cons)(L_n)((function(){var $m; return function(){return $m || ($m = resolve(L_series)(L_func)((function(){var $m; return function(){return $m || ($m = resolve(L_func)(L_n))}})()))}})())}})}})())},
  function(){return resolve(L_define)(function(){return "from"})(function(){return 1})(function(){return "from n = series ++ n"})((function(){var $m; return function(){return $m || ($m = function(L_n){return resolve(L_series)(L_$o$o)(L_n)})}})())},
  function(){return resolve(L_define)(function(){return "fromBy"})(function(){return 2})(function(){return "fromBy n inc = series ((+) inc) n"})((function(){var $m; return function(){return $m || ($m = function(L_n){return function(L_inc){return resolve(L_series)((function(){var $m; return function(){return $m || ($m = resolve(L_$o)(L_inc))}})())(L_n)}})}})())},
  function(){return resolve(L_define)(function(){return "fromTo"})(function(){return 2})(function(){return "fromTo n m = takeWhile ((>) m) (from n)"})((function(){var $m; return function(){return $m || ($m = function(L_n){return function(L_m){return resolve(L_takeWhile)((function(){var $m; return function(){return $m || ($m = resolve(L_$z)(L_m))}})())((function(){var $m; return function(){return $m || ($m = resolve(L_from)(L_n))}})())}})}})())},
  function(){return resolve(L_define)(function(){return "fromToBy"})(function(){return 3})(function(){return "fromToBy n m inc = takeWhile ((>) m) (fromBy n inc)"})((function(){var $m; return function(){return $m || ($m = function(L_n){return function(L_m){return function(L_inc){return resolve(L_takeWhile)((function(){var $m; return function(){return $m || ($m = resolve(L_$z)(L_m))}})())((function(){var $m; return function(){return $m || ($m = resolve(L_fromBy)(L_n)(L_inc))}})())}}})}})())},
  function(){return resolve(L_define)(function(){return "count"})(function(){return 2})(function(){return "count x l = countIf (eq x) l"})((function(){var $m; return function(){return $m || ($m = function(L_x){return function(L_l){return resolve(L_countIf)((function(){var $m; return function(){return $m || ($m = resolve(L_eq)(L_x))}})())(L_l)}})}})())},
  function(){return resolve(L_define)(function(){return "countIf"})(function(){return 2})(function(){return "countIf f l = (eq l nil) 0\n  + (f (head l) 1 0) (countIf f (tail l))"})((function(){var $m; return function(){return $m || ($m = function(L_f){return function(L_l){return resolve(L_eq)(L_l)(L_nil)(function(){return 0})((function(){var $m; return function(){return $m || ($m = resolve(L_$o)((function(){var $m; return function(){return $m || ($m = resolve(L_f)((function(){var $m; return function(){return $m || ($m = resolve(L_head)(L_l))}})())(function(){return 1})(function(){return 0}))}})())((function(){var $m; return function(){return $m || ($m = resolve(L_countIf)(L_f)((function(){var $m; return function(){return $m || ($m = resolve(L_tail)(L_l))}})()))}})()))}})())}})}})())},
  function(){return resolve(L_define)(function(){return "countIfNot"})(function(){return 2})(function(){return "countIfNot f l = countIf (\\x. not (f x)) l"})((function(){var $m; return function(){return $m || ($m = function(L_f){return function(L_l){return resolve(L_countIf)((function(){var $m; return function(){return $m || ($m = function(L_x){return resolve(L_not)((function(){var $m; return function(){return $m || ($m = resolve(L_f)(L_x))}})())})}})())(L_l)}})}})())},
  function(){return resolve(L_define)(function(){return "odds"})(function(){return 1})(function(){return "odds l = l\n  \\h t D . [h | evens t]\n  nil"})((function(){var $m; return function(){return $m || ($m = function(L_l){return resolve(L_l)((function(){var $m; return function(){return $m || ($m = function(L_h){return function(L_t){return function(L_D){return resolve(L_cons)(L_h)((function(){var $m; return function(){return $m || ($m = resolve(L_evens)(L_t))}})())}}})}})())(L_nil)})}})())},
  function(){return resolve(L_define)(function(){return "evens"})(function(){return 1})(function(){return "evens l = l\n  \\h t D . odds t\n  nil"})((function(){var $m; return function(){return $m || ($m = function(L_l){return resolve(L_l)((function(){var $m; return function(){return $m || ($m = function(L_h){return function(L_t){return function(L_D){return resolve(L_odds)(L_t)}}})}})())(L_nil)})}})())},
  function(){return resolve(L_define)(function(){return "cleave"})(function(){return 1})(function(){return "cleave l = [(evens l) | (odds l)]"})((function(){var $m; return function(){return $m || ($m = function(L_l){return resolve(L_cons)((function(){var $m; return function(){return $m || ($m = resolve(L_evens)(L_l))}})())((function(){var $m; return function(){return $m || ($m = resolve(L_odds)(L_l))}})())})}})())},
  function(){return resolve(L_define)(function(){return "merge"})(function(){return 3})(function(){return "merge cmp a b = a\n  \\ah at D . b\n    \\bh bt D . cmp ah bh\n      [ah | (merge cmp at b)]\n      [bh | (merge cmp a bt)]\n    a\n  b"})((function(){var $m; return function(){return $m || ($m = function(L_cmp){return function(L_a){return function(L_b){return resolve(L_a)((function(){var $m; return function(){return $m || ($m = function(L_ah){return function(L_at){return function(L_D){return resolve(L_b)((function(){var $m; return function(){return $m || ($m = function(L_bh){return function(L_bt){return function(L_D_0){return resolve(L_cmp)(L_ah)(L_bh)((function(){var $m; return function(){return $m || ($m = resolve(L_cons)(L_ah)((function(){var $m; return function(){return $m || ($m = resolve(L_merge)(L_cmp)(L_at)(L_b))}})()))}})())((function(){var $m; return function(){return $m || ($m = resolve(L_cons)(L_bh)((function(){var $m; return function(){return $m || ($m = resolve(L_merge)(L_cmp)(L_a)(L_bt))}})()))}})())}}})}})())(L_a)}}})}})())(L_b)}}})}})())},
  function(){return resolve(L_define)(function(){return "mergeSort"})(function(){return 2})(function(){return "mergeSort cmp l = l\n  \\h t D . eq (tail l) nil\n    l\n    do\n      cl = cleave l\n      e = head cl\n      o = tail cl\n      merge cmp (mergeSort cmp e) (mergeSort cmp o)\n  nil"})((function(){var $m; return function(){return $m || ($m = function(L_cmp){return function(L_l){return resolve(L_l)((function(){var $m; return function(){return $m || ($m = function(L_h){return function(L_t){return function(L_D){return resolve(L_eq)((function(){var $m; return function(){return $m || ($m = resolve(L_tail)(L_l))}})())(L_nil)(L_l)(function(){
var L_o, L_e, L_cl;

L_o = (function(){var $m; return function(){return $m || ($m = resolve(L_tail)(L_cl))}})();

L_e = (function(){var $m; return function(){return $m || ($m = resolve(L_head)(L_cl))}})();

L_cl = (function(){var $m; return function(){return $m || ($m = resolve(L_cleave)(L_l))}})();
return resolve(L_merge)(L_cmp)((function(){var $m; return function(){return $m || ($m = resolve(L_mergeSort)(L_cmp)(L_e))}})())((function(){var $m; return function(){return $m || ($m = resolve(L_mergeSort)(L_cmp)(L_o))}})())})}}})}})())(L_nil)}})}})())},
  function(){return resolve(L_define)(function(){return "sort"})(function(){return 1})(function(){return "sort l = sortBy lte l"})((function(){var $m; return function(){return $m || ($m = function(L_l){return resolve(L_sortBy)(L_lte)(L_l)})}})())},
  function(){return resolve(L_define)(function(){return "sortBy"})(function(){return 2})(function(){return "sortBy cmp l = mergeSort cmp l"})((function(){var $m; return function(){return $m || ($m = function(L_cmp){return function(L_l){return resolve(L_mergeSort)(L_cmp)(L_l)}})}})())},
  function(){return resolve(L_addToken)(function(){return "->"})},
  function(){return resolve(L_define)(function(){return "mkStr"})(function(){return 1})(function(){return "mkStr tok = concat['\"' (tokenString tok) '\"']"})((function(){var $m; return function(){return $m || ($m = function(L_tok){return resolve(L_strCat)((function(){var $m; return function(){return $m || ($m = resolve(L_cons)(function(){return "\""})((function(){var $m; return function(){return $m || ($m = resolve(L_cons)((function(){var $m; return function(){return $m || ($m = resolve(L_tokenString)(L_tok))}})())((function(){var $m; return function(){return $m || ($m = resolve(L_cons)(function(){return "\""})(L_nil))}})()))}})()))}})())})}})())},
  function(){return resolve(L_defMacro)(function(){return "defCase"})((function(){var $m; return function(){return $m || ($m = function(L_list){return (function(){

var L_t3, L_h3, L_t2, L_h2, L_t1, L_h1;

L_t3 = (function(){var $m; return function(){return $m || ($m = resolve(L_tail)(L_t2))}})();

L_h3 = (function(){var $m; return function(){return $m || ($m = resolve(L_head)(L_t2))}})();

L_t2 = (function(){var $m; return function(){return $m || ($m = resolve(L_tail)(L_t1))}})();

L_h2 = (function(){var $m; return function(){return $m || ($m = resolve(L_head)(L_t1))}})();

L_t1 = (function(){var $m; return function(){return $m || ($m = resolve(L_tail)(L_list))}})();

L_h1 = (function(){var $m; return function(){return $m || ($m = resolve(L_head)(L_list))}})();
return resolve(L_and)((function(){var $m; return function(){return $m || ($m = resolve(L_isCons)(L_list))}})())((function(){var $m; return function(){return $m || ($m = resolve(L_and)((function(){var $m; return function(){return $m || ($m = resolve(L_isCons)(L_t1))}})())((function(){var $m; return function(){return $m || ($m = resolve(L_and)((function(){var $m; return function(){return $m || ($m = resolve(L_isCons)(L_t2))}})())((function(){var $m; return function(){return $m || ($m = resolve(L_and)((function(){var $m; return function(){return $m || ($m = resolve(L_isTokenString)(L_h2)(function(){return "."}))}})())(L_true))}})()))}})()))}})())((function(){var $m; return function(){return $m || ($m = resolve(L_makeCaseArgs)(L_list)((function(){var $m; return function(){return $m || ($m = resolve(L_mkStr)(L_h1))}})())((function(){var $m; return function(){return $m || ($m = resolve(L_mkStr)(L_h3))}})())(L_t3)(L_id))}})())((function(){var $m; return function(){return $m || ($m = resolve(L_parseErr)(function(){return "Error in case definition -- expected func.name args | condition -> action, but got "})(L_list))}})())})()})}})())},
  function(){return resolve(L_define)(function(){return "makeCaseArgs"})(function(){return 5})(function(){return "makeCaseArgs orig funcName altName rest args = rest\n  \\h t D . isTokenString h '|'\n    makeCaseCondition orig funcName altName (args nil) t id\n    makeCaseArgs orig funcName altName t (dlPush args h)\n  parseErr \"Error in case definition -- expected func.name args | condition -> action, but got \" orig"})((function(){var $m; return function(){return $m || ($m = function(L_orig){return function(L_funcName){return function(L_altName){return function(L_rest){return function(L_args){return resolve(L_rest)((function(){var $m; return function(){return $m || ($m = function(L_h){return function(L_t){return function(L_D){return resolve(L_isTokenString)(L_h)(function(){return "|"})((function(){var $m; return function(){return $m || ($m = resolve(L_makeCaseCondition)(L_orig)(L_funcName)(L_altName)((function(){var $m; return function(){return $m || ($m = resolve(L_args)(L_nil))}})())(L_t)(L_id))}})())((function(){var $m; return function(){return $m || ($m = resolve(L_makeCaseArgs)(L_orig)(L_funcName)(L_altName)(L_t)((function(){var $m; return function(){return $m || ($m = resolve(L_dlPush)(L_args)(L_h))}})()))}})())}}})}})())((function(){var $m; return function(){return $m || ($m = resolve(L_parseErr)(function(){return "Error in case definition -- expected func.name args | condition -> action, but got "})(L_orig))}})())}}}}})}})())},
  function(){return resolve(L_define)(function(){return "makeCaseCondition"})(function(){return 6})(function(){return "makeCaseCondition orig funcName altName args rest cond = rest\n  \\h t D . isTokenString h '->'\n    foldr1 append [['altDef' funcName altName (length args) '\\\\'] args ['.' (cond nil) ['some' t] 'none']]\n    makeCaseCondition orig funcName altName args t (dlPush cond h)\n parseErr \"Error in case definition -- expected func.name args | condition -> action, but got \" orig"})((function(){var $m; return function(){return $m || ($m = function(L_orig){return function(L_funcName){return function(L_altName){return function(L_args){return function(L_rest){return function(L_cond){return resolve(L_rest)((function(){var $m; return function(){return $m || ($m = function(L_h){return function(L_t){return function(L_D){return resolve(L_isTokenString)(L_h)(function(){return "->"})((function(){var $m; return function(){return $m || ($m = resolve(L_foldr1)(L_append)((function(){var $m; return function(){return $m || ($m = resolve(L_cons)((function(){var $m; return function(){return $m || ($m = resolve(L_cons)(function(){return "altDef"})((function(){var $m; return function(){return $m || ($m = resolve(L_cons)(L_funcName)((function(){var $m; return function(){return $m || ($m = resolve(L_cons)(L_altName)((function(){var $m; return function(){return $m || ($m = resolve(L_cons)((function(){var $m; return function(){return $m || ($m = resolve(L_length)(L_args))}})())((function(){var $m; return function(){return $m || ($m = resolve(L_cons)(function(){return "\\"})(L_nil))}})()))}})()))}})()))}})()))}})())((function(){var $m; return function(){return $m || ($m = resolve(L_cons)(L_args)((function(){var $m; return function(){return $m || ($m = resolve(L_cons)((function(){var $m; return function(){return $m || ($m = resolve(L_cons)(function(){return "."})((function(){var $m; return function(){return $m || ($m = resolve(L_cons)((function(){var $m; return function(){return $m || ($m = resolve(L_cond)(L_nil))}})())((function(){var $m; return function(){return $m || ($m = resolve(L_cons)((function(){var $m; return function(){return $m || ($m = resolve(L_cons)(function(){return "some"})((function(){var $m; return function(){return $m || ($m = resolve(L_cons)(L_t)(L_nil))}})()))}})())((function(){var $m; return function(){return $m || ($m = resolve(L_cons)(function(){return "none"})(L_nil))}})()))}})()))}})()))}})())(L_nil))}})()))}})()))}})()))}})())((function(){var $m; return function(){return $m || ($m = resolve(L_makeCaseCondition)(L_orig)(L_funcName)(L_altName)(L_args)(L_t)((function(){var $m; return function(){return $m || ($m = resolve(L_dlPush)(L_cond)(L_h))}})()))}})())}}})}})())((function(){var $m; return function(){return $m || ($m = resolve(L_parseErr)(function(){return "Error in case definition -- expected func.name args | condition -> action, but got "})(L_orig))}})())}}}}}})}})())},
  function(){return resolve(L_altDef)(function(){return "show"})(function(){return "some"})(function(){return 1})((function(){var $m; return function(){return $m || ($m = function(L_obj){return resolve(L_hasType)(L_obj)(L_some)((function(){var $m; return function(){return $m || ($m = resolve(L_some)((function(){var $m; return function(){return $m || ($m = resolve(L_strCat)((function(){var $m; return function(){return $m || ($m = resolve(L_cons)(function(){return "Some("})((function(){var $m; return function(){return $m || ($m = resolve(L_cons)((function(){var $m; return function(){return $m || ($m = resolve(L_obj)(L_id)(L_false))}})())((function(){var $m; return function(){return $m || ($m = resolve(L_cons)(function(){return ")"})(L_nil))}})()))}})()))}})()))}})()))}})())(L_none)})}})())},
  function(){return resolve(L_altDef)(function(){return "show"})(function(){return "some2"})(function(){return 1})((function(){var $m; return function(){return $m || ($m = function(L_obj){return resolve(L_hasType)(L_obj)(L_some2)((function(){var $m; return function(){return $m || ($m = resolve(L_some)((function(){var $m; return function(){return $m || ($m = resolve(L_strCat)((function(){var $m; return function(){return $m || ($m = resolve(L_cons)(function(){return "Some2("})((function(){var $m; return function(){return $m || ($m = resolve(L_cons)((function(){var $m; return function(){return $m || ($m = resolve(L_obj)((function(){var $m; return function(){return $m || ($m = function(L_a){return function(L_b){return resolve(L_cons)(L_a)((function(){var $m; return function(){return $m || ($m = resolve(L_cons)(function(){return ", "})((function(){var $m; return function(){return $m || ($m = resolve(L_cons)(L_b)(L_nil))}})()))}})())}})}})())(L_false))}})())((function(){var $m; return function(){return $m || ($m = resolve(L_cons)(function(){return ")"})(L_nil))}})()))}})()))}})()))}})()))}})())(L_none)})}})())},
  function(){return resolve(L_altDef)(function(){return "show"})(function(){return "none"})(function(){return 1})((function(){var $m; return function(){return $m || ($m = function(L_obj){return resolve(L_hasType)(L_obj)(L_none)((function(){var $m; return function(){return $m || ($m = resolve(L_some)(function(){return "None"}))}})())(L_none)})}})())},
  function(){return resolve(L_altDef)(function(){return "show"})(function(){return "left"})(function(){return 1})((function(){var $m; return function(){return $m || ($m = function(L_obj){return resolve(L_hasType)(L_obj)(L_left)((function(){var $m; return function(){return $m || ($m = resolve(L_some)((function(){var $m; return function(){return $m || ($m = resolve(L_strCat)((function(){var $m; return function(){return $m || ($m = resolve(L_cons)(function(){return "Left("})((function(){var $m; return function(){return $m || ($m = resolve(L_cons)((function(){var $m; return function(){return $m || ($m = resolve(L_obj)(L_id)(L_id))}})())((function(){var $m; return function(){return $m || ($m = resolve(L_cons)(function(){return ")"})(L_nil))}})()))}})()))}})()))}})()))}})())(L_none)})}})())},
  function(){return resolve(L_altDef)(function(){return "show"})(function(){return "right"})(function(){return 1})((function(){var $m; return function(){return $m || ($m = function(L_obj){return resolve(L_hasType)(L_obj)(L_right)((function(){var $m; return function(){return $m || ($m = resolve(L_some)((function(){var $m; return function(){return $m || ($m = resolve(L_strCat)((function(){var $m; return function(){return $m || ($m = resolve(L_cons)(function(){return "Right("})((function(){var $m; return function(){return $m || ($m = resolve(L_cons)((function(){var $m; return function(){return $m || ($m = resolve(L_obj)(L_id)(L_id))}})())((function(){var $m; return function(){return $m || ($m = resolve(L_cons)(function(){return ")"})(L_nil))}})()))}})()))}})()))}})()))}})())(L_none)})}})())},
  function(){return resolve(L_altDef)(function(){return "show"})(function(){return "nil"})(function(){return 1})((function(){var $m; return function(){return $m || ($m = function(L_obj){return resolve(L_hasType)(L_obj)(L_nil)((function(){var $m; return function(){return $m || ($m = resolve(L_some)(function(){return "nil"}))}})())(L_none)})}})())},
  function(){return resolve(L_altDef)(function(){return "show"})(function(){return "assoc"})(function(){return 1})((function(){var $m; return function(){return $m || ($m = function(L_obj){return resolve(L_isAlist)(L_obj)((function(){var $m; return function(){return $m || ($m = resolve(L_some)((function(){var $m; return function(){return $m || ($m = resolve(L_strCat)((function(){var $m; return function(){return $m || ($m = resolve(L_flatten)((function(){var $m; return function(){return $m || ($m = resolve(L_cons)(function(){return "{"})((function(){var $m; return function(){return $m || ($m = resolve(L_cons)((function(){var $m; return function(){return $m || ($m = resolve(L_intersperse)((function(){var $m; return function(){return $m || ($m = resolve(L_map)((function(){var $m; return function(){return $m || ($m = function(L_item){return resolve(L_cons)((function(){var $m; return function(){return $m || ($m = resolve(L_show)((function(){var $m; return function(){return $m || ($m = resolve(L_head)(L_item))}})()))}})())((function(){var $m; return function(){return $m || ($m = resolve(L_cons)(function(){return ":"})((function(){var $m; return function(){return $m || ($m = resolve(L_cons)((function(){var $m; return function(){return $m || ($m = resolve(L_show)((function(){var $m; return function(){return $m || ($m = resolve(L_tail)(L_item))}})()))}})())(L_nil))}})()))}})())})}})())(L_obj))}})())(function(){return " "}))}})())((function(){var $m; return function(){return $m || ($m = resolve(L_cons)(function(){return "}"})(L_nil))}})()))}})()))}})()))}})()))}})()))}})())(L_none)})}})())},
  function(){return resolve(L_altDef)(function(){return "show"})(function(){return "hamt"})(function(){return 1})((function(){var $m; return function(){return $m || ($m = function(L_obj){return resolve(L_hasType)(L_obj)(L_hamt)((function(){var $m; return function(){return $m || ($m = resolve(L_some)((function(){var $m; return function(){return $m || ($m = resolve(L_strCat)((function(){var $m; return function(){return $m || ($m = resolve(L_flatten)((function(){var $m; return function(){return $m || ($m = resolve(L_cons)(function(){return "hamt{"})((function(){var $m; return function(){return $m || ($m = resolve(L_cons)((function(){var $m; return function(){return $m || ($m = resolve(L_intersperse)((function(){var $m; return function(){return $m || ($m = resolve(L_map)((function(){var $m; return function(){return $m || ($m = function(L_item){return resolve(L_cons)((function(){var $m; return function(){return $m || ($m = resolve(L_show)((function(){var $m; return function(){return $m || ($m = resolve(L_head)(L_item))}})()))}})())((function(){var $m; return function(){return $m || ($m = resolve(L_cons)(function(){return ":"})((function(){var $m; return function(){return $m || ($m = resolve(L_cons)((function(){var $m; return function(){return $m || ($m = resolve(L_show)((function(){var $m; return function(){return $m || ($m = resolve(L_tail)(L_item))}})()))}})())(L_nil))}})()))}})())})}})())((function(){var $m; return function(){return $m || ($m = resolve(L_hamtPairs)(L_obj))}})()))}})())(function(){return " "}))}})())((function(){var $m; return function(){return $m || ($m = resolve(L_cons)(function(){return "}"})(L_nil))}})()))}})()))}})()))}})()))}})()))}})())(L_none)})}})())},
  function(){return resolve(L_altDef)(function(){return "show"})(function(){return "cons"})(function(){return 1})((function(){var $m; return function(){return $m || ($m = function(L_obj){return resolve(L_hasType)(L_obj)(L_cons)((function(){var $m; return function(){return $m || ($m = resolve(L_some)((function(){var $m; return function(){return $m || ($m = resolve(L_strCat)((function(){var $m; return function(){return $m || ($m = resolve(L_flatten)((function(){var $m; return function(){return $m || ($m = resolve(L_cons)(function(){return "["})((function(){var $m; return function(){return $m || ($m = resolve(L_cons)((function(){var $m; return function(){return $m || ($m = resolve(L_show)((function(){var $m; return function(){return $m || ($m = resolve(L_head)(L_obj))}})()))}})())((function(){var $m; return function(){return $m || ($m = resolve(L_cons)((function(){var $m; return function(){return $m || ($m = resolve(L_showConsElements)((function(){var $m; return function(){return $m || ($m = resolve(L_tail)(L_obj))}})()))}})())((function(){var $m; return function(){return $m || ($m = resolve(L_cons)(function(){return "]"})(L_nil))}})()))}})()))}})()))}})()))}})()))}})()))}})())(L_none)})}})())},
  function(){return resolve(L_define)(function(){return "showConsElements"})(function(){return 1})(function(){return "showConsElements list = isCons list\n  [' ' (show (head list)) (showConsElements (tail list))]\n  isNil list\n    ''\n    [' | ' (show list)]"})((function(){var $m; return function(){return $m || ($m = function(L_list){return resolve(L_isCons)(L_list)((function(){var $m; return function(){return $m || ($m = resolve(L_cons)(function(){return " "})((function(){var $m; return function(){return $m || ($m = resolve(L_cons)((function(){var $m; return function(){return $m || ($m = resolve(L_show)((function(){var $m; return function(){return $m || ($m = resolve(L_head)(L_list))}})()))}})())((function(){var $m; return function(){return $m || ($m = resolve(L_cons)((function(){var $m; return function(){return $m || ($m = resolve(L_showConsElements)((function(){var $m; return function(){return $m || ($m = resolve(L_tail)(L_list))}})()))}})())(L_nil))}})()))}})()))}})())((function(){var $m; return function(){return $m || ($m = resolve(L_isNil)(L_list)(function(){return ""})((function(){var $m; return function(){return $m || ($m = resolve(L_cons)(function(){return " | "})((function(){var $m; return function(){return $m || ($m = resolve(L_cons)((function(){var $m; return function(){return $m || ($m = resolve(L_show)(L_list))}})())(L_nil))}})()))}})()))}})())})}})())},
  function(){return resolve(L_altDef)(function(){return "bind"})(function(){return "option"})(function(){return 2})((function(){var $m; return function(){return $m || ($m = function(L_opt){return function(L_cont){return resolve(L_or)((function(){var $m; return function(){return $m || ($m = resolve(L_hasType)(L_opt)(L_some))}})())((function(){var $m; return function(){return $m || ($m = resolve(L_hasType)(L_opt)(L_none))}})())((function(){var $m; return function(){return $m || ($m = resolve(L_some)((function(){var $m; return function(){return $m || ($m = resolve(L_opt)((function(){var $m; return function(){return $m || ($m = function(L_value){return resolve(L_cont)(L_value)})}})())(L_none))}})()))}})())(L_none)}})}})())},
  function(){return resolve(L_altDef)(function(){return "bind"})(function(){return "either"})(function(){return 2})((function(){var $m; return function(){return $m || ($m = function(L_either){return function(L_cont){return resolve(L_or)((function(){var $m; return function(){return $m || ($m = resolve(L_hasType)(L_either)(L_left))}})())((function(){var $m; return function(){return $m || ($m = resolve(L_hasType)(L_either)(L_right))}})())((function(){var $m; return function(){return $m || ($m = resolve(L_some)((function(){var $m; return function(){return $m || ($m = resolve(L_either)((function(){var $m; return function(){return $m || ($m = function(L__){return resolve(L_either)})}})())((function(){var $m; return function(){return $m || ($m = function(L_value){return resolve(L_cont)(L_value)})}})()))}})()))}})())(L_none)}})}})())},
  function(){return resolve(L_defMacro)(function(){return "defWrapper"})((function(){var $m; return function(){return $m || ($m = function(L_list){return resolve(L_grabLeftOfArrow)(L_list)(L_nil)((function(){var $m; return function(){return $m || ($m = function(L_left){return function(L_right){return resolve(L_cons)(function(){return "override"})((function(){var $m; return function(){return $m || ($m = resolve(L_cons)((function(){var $m; return function(){return $m || ($m = resolve(L_strCat)((function(){var $m; return function(){return $m || ($m = resolve(L_cons)(function(){return "'"})((function(){var $m; return function(){return $m || ($m = resolve(L_cons)((function(){var $m; return function(){return $m || ($m = resolve(L_strTokenString)((function(){var $m; return function(){return $m || ($m = resolve(L_head)(L_left))}})()))}})())((function(){var $m; return function(){return $m || ($m = resolve(L_cons)(function(){return "'"})(L_nil))}})()))}})()))}})()))}})())((function(){var $m; return function(){return $m || ($m = resolve(L_cons)((function(){var $m; return function(){return $m || ($m = resolve(L_append)((function(){var $m; return function(){return $m || ($m = resolve(L_cons)(function(){return "\\"})((function(){var $m; return function(){return $m || ($m = resolve(L_tail)(L_left))}})()))}})())((function(){var $m; return function(){return $m || ($m = resolve(L_cons)(function(){return "."})(L_right))}})()))}})())(L_nil))}})()))}})())}})}})())})}})())},
  function(){return resolve(L_define)(function(){return "grabLeftOfArrow"})(function(){return 3})(function(){return "grabLeftOfArrow list left cont = isTokenString (head list) '->'\n  cont (reverse left) (tail list)\n  grabLeftOfArrow (tail list) (head list) : left cont"})((function(){var $m; return function(){return $m || ($m = function(L_list){return function(L_left){return function(L_cont){return resolve(L_isTokenString)((function(){var $m; return function(){return $m || ($m = resolve(L_head)(L_list))}})())(function(){return "->"})((function(){var $m; return function(){return $m || ($m = resolve(L_cont)((function(){var $m; return function(){return $m || ($m = resolve(L_reverse)(L_left))}})())((function(){var $m; return function(){return $m || ($m = resolve(L_tail)(L_list))}})()))}})())((function(){var $m; return function(){return $m || ($m = resolve(L_grabLeftOfArrow)((function(){var $m; return function(){return $m || ($m = resolve(L_tail)(L_list))}})())((function(){var $m; return function(){return $m || ($m = resolve(L_cons)((function(){var $m; return function(){return $m || ($m = resolve(L_head)(L_list))}})())(L_left))}})())(L_cont))}})())}}})}})())},
  function(){return resolve(L_override)(function(){return "head"})((function(){var $m; return function(){return $m || ($m = function(L_oldHead){return function(L_list){return resolve(L_assertType)(function(){return "head argument"})(L_cons)(L_list)((function(){var $m; return function(){return $m || ($m = function(L_h){return function(L_t){return resolve(L_h)}})}})())}})}})())},
  function(){return resolve(L_override)(function(){return "tail"})((function(){var $m; return function(){return $m || ($m = function(L_oldTail){return function(L_list){return resolve(L_assertType)(function(){return "tail argument"})(L_cons)(L_list)((function(){var $m; return function(){return $m || ($m = function(L_h){return function(L_t){return resolve(L_t)}})}})())}})}})())},
  function(){return resolve(L_override)(function(){return "hamtWith"})((function(){var $m; return function(){return $m || ($m = function(L_oldHamtWith){return function(L_key){return function(L_value){return function(L_hamt){return resolve(L_oldHamtWith)((function(){var $m; return function(){return $m || ($m = resolve(L_assertType)(function(){return "hamtWith key"})(function(){return "*string"})(L_key))}})())(L_value)(L_hamt)}}}})}})())},
  function(){return resolve(L_define)(function(){return "html"})(function(){return 1})(function(){return "html x = \\f . f x"})((function(){var $m; return function(){return $m || ($m = setDataType(function(L_x){return setType(function(L_f){return resolve(L_f)(L_x)}, 'html')}, 'html'))}})())},
  function(){return resolve(L_defTokenPack)(function(){return "util"})((function(){var $m; return function(){return $m || ($m = resolve(L_cons)((function(){var $m; return function(){return $m || ($m = resolve(L_cons)(function(){return "->"})((function(){var $m; return function(){return $m || ($m = resolve(L_cons)(function(){return "--"})((function(){var $m; return function(){return $m || ($m = resolve(L_cons)(function(){return "++"})(L_nil))}})()))}})()))}})())((function(){var $m; return function(){return $m || ($m = resolve(L_cons)((function(){var $m; return function(){return $m || ($m = resolve(L_cons)((function(){var $m; return function(){return $m || ($m = resolve(L_cons)(function(){return "js["})(function(){return "]"}))}})())(L_nil))}})())((function(){var $m; return function(){return $m || ($m = resolve(L_cons)(L_nil)(L_nil))}})()))}})()))}})())},
  function(){return resolve(L_addStdTokenPacks)((function(){var $m; return function(){return $m || ($m = resolve(L_cons)(function(){return "util"})(L_nil))}})())}]);
