L_runMonads([
  function(){return L_define()(function(){return "if"})(function(){return 0})(function(){return "if = id"})(L_id)},
  function(){return L_define()(function(){return "iszero"})(function(){return 0})(function(){return "iszero = eq 0"})((function(){var $m; return function(){return $m || ($m = L_eq()(function(){return 0}))}})())},
  function(){return L_define()(function(){return "positive"})(function(){return 0})(function(){return "positive = 0 <"})((function(){var $m; return function(){return $m || ($m = L_$y()(function(){return 0}))}})())},
  function(){return L_addToken()(function(){return "--"})},
  function(){return L_addToken()(function(){return "++"})},
  function(){return L_define()(function(){return "--"})(function(){return 0})(function(){return "-- = (flip (-)) 1"})((function(){var $m; return function(){return $m || ($m = L_flip()(L_$_)(function(){return 1}))}})())},
  function(){return L_define()(function(){return "++"})(function(){return 0})(function(){return "++ = (1 +)"})((function(){var $m; return function(){return $m || ($m = L_$o()(function(){return 1}))}})())},
  function(){return L_define()(function(){return "intercalate"})(function(){return 2})(function(){return "intercalate x l = concat (intersperse x l)"})((function(){var $m; return function(){return $m || ($m = function(L_x){return function(L_l){return L_concat()((function(){var $m; return function(){return $m || ($m = L_intersperse()(L_x)(L_l))}})())}})}})())},
  function(){return L_define()(function(){return "dlempty"})(function(){return 0})(function(){return "dlempty = id"})(L_id)},
  function(){return L_define()(function(){return "dl"})(function(){return 1})(function(){return "dl item = \\rest . [item | rest]"})((function(){var $m; return function(){return $m || ($m = setDataType(function(L_item){return setType(function(L_rest){return L_cons()(L_item)(L_rest)}, 'dl')}, 'dl'))}})())},
  function(){return L_define()(function(){return "dlPush"})(function(){return 2})(function(){return "dlPush list item = dlAppend list (dl item)"})((function(){var $m; return function(){return $m || ($m = function(L_list){return function(L_item){return L_dlAppend()(L_list)((function(){var $m; return function(){return $m || ($m = L_dl()(L_item))}})())}})}})())},
  function(){return L_define()(function(){return "dlAppend"})(function(){return 2})(function(){return "dlAppend a b = \\rest . a (b rest)"})((function(){var $m; return function(){return $m || ($m = setDataType(function(L_a){return function(L_b){return setType(function(L_rest){return L_a()((function(){var $m; return function(){return $m || ($m = L_b()(L_rest))}})())}, 'dlAppend')}}, 'dlAppend'))}})())},
  function(){return L_define()(function(){return "remove"})(function(){return 2})(function(){return "remove x l = removeIf (eq x) l"})((function(){var $m; return function(){return $m || ($m = function(L_x){return function(L_l){return L_removeIf()((function(){var $m; return function(){return $m || ($m = L_eq()(L_x))}})())(L_l)}})}})())},
  function(){return L_define()(function(){return "removeIf"})(function(){return 2})(function(){return "removeIf f l = filter (compose not f) l"})((function(){var $m; return function(){return $m || ($m = function(L_f){return function(L_l){return L_filter()((function(){var $m; return function(){return $m || ($m = L_compose()(L_not)(L_f))}})())(L_l)}})}})())},
  function(){return L_define()(function(){return "any"})(function(){return 2})(function(){return "any f l = find f l (\\el . true) false"})((function(){var $m; return function(){return $m || ($m = function(L_f){return function(L_l){return L_find()(L_f)(L_l)((function(){var $m; return function(){return $m || ($m = function(L_el){return L_true()})}})())(L_false)}})}})())},
  function(){return L_define()(function(){return "all"})(function(){return 2})(function(){return "all f l = not any (compose not f) l"})((function(){var $m; return function(){return $m || ($m = function(L_f){return function(L_l){return L_not()(L_any)((function(){var $m; return function(){return $m || ($m = L_compose()(L_not)(L_f))}})())(L_l)}})}})())},
  function(){return L_define()(function(){return "take"})(function(){return 2})(function(){return "take n list = positive n\n  list\n    \\h t D . cons h (take (-- n) t)\n    nil\n  nil"})((function(){var $m; return function(){return $m || ($m = function(L_n){return function(L_list){return L_positive()(L_n)((function(){var $m; return function(){return $m || ($m = L_list()((function(){var $m; return function(){return $m || ($m = function(L_h){return function(L_t){return function(L_D){return L_cons()(L_h)((function(){var $m; return function(){return $m || ($m = L_take()((function(){var $m; return function(){return $m || ($m = L_$_$_()(L_n))}})())(L_t))}})())}}})}})())(L_nil))}})())(L_nil)}})}})())},
  function(){return L_define()(function(){return "takeWhile"})(function(){return 2})(function(){return "takeWhile predicate list = list\n  \\h t D . predicate (head list)\n    cons h (takeWhile predicate t)\n    nil\n  nil"})((function(){var $m; return function(){return $m || ($m = function(L_predicate){return function(L_list){return L_list()((function(){var $m; return function(){return $m || ($m = function(L_h){return function(L_t){return function(L_D){return L_predicate()((function(){var $m; return function(){return $m || ($m = L_head()(L_list))}})())((function(){var $m; return function(){return $m || ($m = L_cons()(L_h)((function(){var $m; return function(){return $m || ($m = L_takeWhile()(L_predicate)(L_t))}})()))}})())(L_nil)}}})}})())(L_nil)}})}})())},
  function(){return L_define()(function(){return "drop"})(function(){return 2})(function(){return "drop x list = positive x\n  list\n    \\h t D . drop (-- x) t\n    nil\n  list"})((function(){var $m; return function(){return $m || ($m = function(L_x){return function(L_list){return L_positive()(L_x)((function(){var $m; return function(){return $m || ($m = L_list()((function(){var $m; return function(){return $m || ($m = function(L_h){return function(L_t){return function(L_D){return L_drop()((function(){var $m; return function(){return $m || ($m = L_$_$_()(L_x))}})())(L_t)}}})}})())(L_nil))}})())(L_list)}})}})())},
  function(){return L_define()(function(){return "dropWhile"})(function(){return 2})(function(){return "dropWhile predicate list = list\n  \\h t D . predicate h\n    dropWhile predicate t\n    list\n  nil"})((function(){var $m; return function(){return $m || ($m = function(L_predicate){return function(L_list){return L_list()((function(){var $m; return function(){return $m || ($m = function(L_h){return function(L_t){return function(L_D){return L_predicate()(L_h)((function(){var $m; return function(){return $m || ($m = L_dropWhile()(L_predicate)(L_t))}})())(L_list)}}})}})())(L_nil)}})}})())},
  function(){return L_define()(function(){return "dropLast"})(function(){return 2})(function(){return "dropLast n list = reverse (drop n (reverse list))"})((function(){var $m; return function(){return $m || ($m = function(L_n){return function(L_list){return L_reverse()((function(){var $m; return function(){return $m || ($m = L_drop()(L_n)((function(){var $m; return function(){return $m || ($m = L_reverse()(L_list))}})()))}})())}})}})())},
  function(){return L_define()(function(){return "box"})(function(){return 2})(function(){return "box n list = list == nil\n  nil\n  [(take n list) | box n (drop n list)]"})((function(){var $m; return function(){return $m || ($m = function(L_n){return function(L_list){return L_$p$p()(L_list)(L_nil)(L_nil)((function(){var $m; return function(){return $m || ($m = L_cons()((function(){var $m; return function(){return $m || ($m = L_take()(L_n)(L_list))}})())((function(){var $m; return function(){return $m || ($m = L_box()(L_n)((function(){var $m; return function(){return $m || ($m = L_drop()(L_n)(L_list))}})()))}})()))}})())}})}})())},
  function(){return L_define()(function(){return "at"})(function(){return 2})(function(){return "at l x = (x == 0) (head l) (at (tail l) (-- (x) ) )"})((function(){var $m; return function(){return $m || ($m = function(L_l){return function(L_x){return L_$p$p()(L_x)(function(){return 0})((function(){var $m; return function(){return $m || ($m = L_head()(L_l))}})())((function(){var $m; return function(){return $m || ($m = L_at()((function(){var $m; return function(){return $m || ($m = L_tail()(L_l))}})())((function(){var $m; return function(){return $m || ($m = L_$_$_()(L_x))}})()))}})())}})}})())},
  function(){return L_define()(function(){return "series"})(function(){return 2})(function(){return "series func n = [n | (series func (func n))]"})((function(){var $m; return function(){return $m || ($m = function(L_func){return function(L_n){return L_cons()(L_n)((function(){var $m; return function(){return $m || ($m = L_series()(L_func)((function(){var $m; return function(){return $m || ($m = L_func()(L_n))}})()))}})())}})}})())},
  function(){return L_define()(function(){return "from"})(function(){return 1})(function(){return "from n = series ++ n"})((function(){var $m; return function(){return $m || ($m = function(L_n){return L_series()(L_$o$o)(L_n)})}})())},
  function(){return L_define()(function(){return "fromBy"})(function(){return 2})(function(){return "fromBy n inc = series ((+) inc) n"})((function(){var $m; return function(){return $m || ($m = function(L_n){return function(L_inc){return L_series()((function(){var $m; return function(){return $m || ($m = L_$o()(L_inc))}})())(L_n)}})}})())},
  function(){return L_define()(function(){return "fromTo"})(function(){return 2})(function(){return "fromTo n m = takeWhile ((>) m) (from n)"})((function(){var $m; return function(){return $m || ($m = function(L_n){return function(L_m){return L_takeWhile()((function(){var $m; return function(){return $m || ($m = L_$z()(L_m))}})())((function(){var $m; return function(){return $m || ($m = L_from()(L_n))}})())}})}})())},
  function(){return L_define()(function(){return "fromToBy"})(function(){return 3})(function(){return "fromToBy n m inc = takeWhile ((>) m) (fromBy n inc)"})((function(){var $m; return function(){return $m || ($m = function(L_n){return function(L_m){return function(L_inc){return L_takeWhile()((function(){var $m; return function(){return $m || ($m = L_$z()(L_m))}})())((function(){var $m; return function(){return $m || ($m = L_fromBy()(L_n)(L_inc))}})())}}})}})())},
  function(){return L_define()(function(){return "count"})(function(){return 2})(function(){return "count x l = countIf (eq x) l"})((function(){var $m; return function(){return $m || ($m = function(L_x){return function(L_l){return L_countIf()((function(){var $m; return function(){return $m || ($m = L_eq()(L_x))}})())(L_l)}})}})())},
  function(){return L_define()(function(){return "countIf"})(function(){return 2})(function(){return "countIf f l = (eq l nil) 0\n  + (f (head l) 1 0) (countIf f (tail l))"})((function(){var $m; return function(){return $m || ($m = function(L_f){return function(L_l){return L_eq()(L_l)(L_nil)(function(){return 0})((function(){var $m; return function(){return $m || ($m = L_$o()((function(){var $m; return function(){return $m || ($m = L_f()((function(){var $m; return function(){return $m || ($m = L_head()(L_l))}})())(function(){return 1})(function(){return 0}))}})())((function(){var $m; return function(){return $m || ($m = L_countIf()(L_f)((function(){var $m; return function(){return $m || ($m = L_tail()(L_l))}})()))}})()))}})())}})}})())},
  function(){return L_define()(function(){return "countIfNot"})(function(){return 2})(function(){return "countIfNot f l = countIf (\\x. not (f x)) l"})((function(){var $m; return function(){return $m || ($m = function(L_f){return function(L_l){return L_countIf()((function(){var $m; return function(){return $m || ($m = function(L_x){return L_not()((function(){var $m; return function(){return $m || ($m = L_f()(L_x))}})())})}})())(L_l)}})}})())},
  function(){return L_define()(function(){return "odds"})(function(){return 1})(function(){return "odds l = l\n  \\h t D . [h | evens t]\n  nil"})((function(){var $m; return function(){return $m || ($m = function(L_l){return L_l()((function(){var $m; return function(){return $m || ($m = function(L_h){return function(L_t){return function(L_D){return L_cons()(L_h)((function(){var $m; return function(){return $m || ($m = L_evens()(L_t))}})())}}})}})())(L_nil)})}})())},
  function(){return L_define()(function(){return "evens"})(function(){return 1})(function(){return "evens l = l\n  \\h t D . odds t\n  nil"})((function(){var $m; return function(){return $m || ($m = function(L_l){return L_l()((function(){var $m; return function(){return $m || ($m = function(L_h){return function(L_t){return function(L_D){return L_odds()(L_t)}}})}})())(L_nil)})}})())},
  function(){return L_define()(function(){return "cleave"})(function(){return 1})(function(){return "cleave l = [(evens l) | (odds l)]"})((function(){var $m; return function(){return $m || ($m = function(L_l){return L_cons()((function(){var $m; return function(){return $m || ($m = L_evens()(L_l))}})())((function(){var $m; return function(){return $m || ($m = L_odds()(L_l))}})())})}})())},
  function(){return L_define()(function(){return "merge"})(function(){return 3})(function(){return "merge cmp a b = a\n  \\ah at D . b\n    \\bh bt D . cmp ah bh\n      [ah | (merge cmp at b)]\n      [bh | (merge cmp a bt)]\n    a\n  b"})((function(){var $m; return function(){return $m || ($m = function(L_cmp){return function(L_a){return function(L_b){return L_a()((function(){var $m; return function(){return $m || ($m = function(L_ah){return function(L_at){return function(L_D){return L_b()((function(){var $m; return function(){return $m || ($m = function(L_bh){return function(L_bt){return function(L_D_0){return L_cmp()(L_ah)(L_bh)((function(){var $m; return function(){return $m || ($m = L_cons()(L_ah)((function(){var $m; return function(){return $m || ($m = L_merge()(L_cmp)(L_at)(L_b))}})()))}})())((function(){var $m; return function(){return $m || ($m = L_cons()(L_bh)((function(){var $m; return function(){return $m || ($m = L_merge()(L_cmp)(L_a)(L_bt))}})()))}})())}}})}})())(L_a)}}})}})())(L_b)}}})}})())},
  function(){return L_define()(function(){return "mergeSort"})(function(){return 2})(function(){return "mergeSort cmp l = l\n  \\h t D . eq (tail l) nil\n    l\n    do\n      cl = cleave l\n      e = head cl\n      o = tail cl\n      merge cmp (mergeSort cmp e) (mergeSort cmp o)\n  nil"})((function(){var $m; return function(){return $m || ($m = function(L_cmp){return function(L_l){return L_l()((function(){var $m; return function(){return $m || ($m = function(L_h){return function(L_t){return function(L_D){return L_eq()((function(){var $m; return function(){return $m || ($m = L_tail()(L_l))}})())(L_nil)(L_l)(function(){
var L_o, L_e, L_cl;

L_o = (function(){var $m; return function(){return $m || ($m = L_tail()(L_cl))}})();

L_e = (function(){var $m; return function(){return $m || ($m = L_head()(L_cl))}})();

L_cl = (function(){var $m; return function(){return $m || ($m = L_cleave()(L_l))}})();
return L_merge()(L_cmp)((function(){var $m; return function(){return $m || ($m = L_mergeSort()(L_cmp)(L_e))}})())((function(){var $m; return function(){return $m || ($m = L_mergeSort()(L_cmp)(L_o))}})())})}}})}})())(L_nil)}})}})())},
  function(){return L_define()(function(){return "sort"})(function(){return 1})(function(){return "sort l = sortBy lte l"})((function(){var $m; return function(){return $m || ($m = function(L_l){return L_sortBy()(L_lte)(L_l)})}})())},
  function(){return L_define()(function(){return "sortBy"})(function(){return 2})(function(){return "sortBy cmp l = mergeSort cmp l"})((function(){var $m; return function(){return $m || ($m = function(L_cmp){return function(L_l){return L_mergeSort()(L_cmp)(L_l)}})}})())},
  function(){return L_define()(function(){return "html"})(function(){return 1})(function(){return "html x = \\f . f x"})((function(){var $m; return function(){return $m || ($m = setDataType(function(L_x){return setType(function(L_f){return L_f()(L_x)}, 'html')}, 'html'))}})())},
  function(){return L_defTokenPack()(function(){return "util"})((function(){var $m; return function(){return $m || ($m = L_cons()((function(){var $m; return function(){return $m || ($m = L_cons()(function(){return "--"})((function(){var $m; return function(){return $m || ($m = L_cons()(function(){return "++"})(L_nil))}})()))}})())((function(){var $m; return function(){return $m || ($m = L_cons()(L_nil)((function(){var $m; return function(){return $m || ($m = L_cons()(L_nil)(L_nil))}})()))}})()))}})())},
  function(){return L_addStdTokenPacks()((function(){var $m; return function(){return $m || ($m = L_cons()(function(){return "util"})(L_nil))}})())}]);
