// Generated by CoffeeScript 1.6.2
/*
Copyright (C) 2013, Bill Burdick, Tiny Concepts: https://github.com/zot/Leisure

(licensed with ZLIB license)

This software is provided 'as-is', without any express or implied
warranty. In no event will the authors be held liable for any damages
arising from the use of this software.

Permission is granted to anyone to use this software for any purpose,
including commercial applications, and to alter it and redistribute it
freely, subject to the following restrictions:

1. The origin of this software must not be misrepresented; you must not
claim that you wrote the original software. If you use this software
in a product, an acknowledgment in the product documentation would be
appreciated but is not required.

2. Altered source versions must be plainly marked as such, and must not be
misrepresented as being the original software.

3. This notice may not be removed or altered from any source distribution.
*/


/*
Tests for Leisure
*/


(function() {
  var LZ, Nil, T, assertEq, assertEval, assertEvalPrint, assertParse, ast2Json, cons, consFrom, defaultEnv, define, gen, getLambdaBody, getLitVal, getRefName, getValue, identity, json2Ast, readFile, run, runLsr, runMonad, runTests, scan, setDataType, setType, setValue, stateValues, writeFile, _ref, _ref1, _ref2, _ref3;

  Error.stackTraceLimit = 20;

  require('source-map-support').install();

  _ref = require('./node'), readFile = _ref.readFile, writeFile = _ref.writeFile;

  _ref1 = LZ = require('./ast'), define = _ref1.define, scan = _ref1.scan, cons = _ref1.cons, Nil = _ref1.Nil, json2Ast = _ref1.json2Ast, ast2Json = _ref1.ast2Json, getLitVal = _ref1.getLitVal, getRefName = _ref1.getRefName, getLambdaBody = _ref1.getLambdaBody, consFrom = _ref1.consFrom, setType = _ref1.setType, setDataType = _ref1.setDataType;

  _ref2 = T = require('./testing'), run = _ref2.run, runTests = _ref2.runTests, assertParse = _ref2.assertParse, assertEval = _ref2.assertEval, assertEvalPrint = _ref2.assertEvalPrint, assertEq = _ref2.assertEq;

  gen = require('./gen').gen;

  _ref3 = require('./runtime'), stateValues = _ref3.stateValues, runMonad = _ref3.runMonad, identity = _ref3.identity, defaultEnv = _ref3.defaultEnv, setValue = _ref3.setValue, getValue = _ref3.getValue;

  runLsr = function(str) {
    return (runMonad(L_runLine()(L_nil)(function() {
      return str;
    }))).tail()(function() {
      return function(x) {
        throw x();
      };
    })(function() {
      return function(x) {
        return x();
      };
    });
  };

  global.runMonad = runMonad;

  global.setType = setType;

  global.setDataType = setDataType;

  global.defaultEnv = defaultEnv;

  global.identity = identity;

  require('./generatedPrelude');

  runTests('Leisure Full Parser', {
    fullParse1: function() {
      assertEq(String(runLsr("scanLineM 'a +'")), 'Cons[[Token("+", 2) Token("a", 0)]]');
      return assertEq(String(runLsr("scanLineM 'a + b'")), 'Cons[[Token("+", 2) Token("a", 0) Token("b", 4)]]');
    },
    fullParse2: function() {
      return assertEq(String(runLsr("scanLineM 'a + b + c'")), 'Cons[[Token("+", 6) [Token("+", 2) Token("a", 0) Token("b", 4)] Token("c", 8)]]');
    },
    fullParse3: function() {
      return assertEq(runLsr("1+2*3 >= 7 == true"), L_true());
    },
    fullParse4: function() {
      assertEq(runLsr("\\\\ (a = []) . isNil a"), L_true());
      return assertEq(runLsr("\\\\ (a = [1 2 3]) . (head a) == 1"), L_true());
    },
    fullParse5: function() {
      assertEq(runLsr("do (a = 3) a"), 3);
      setValue('fred', 5);
      return assertEq(runLsr("do (a <- getValue 'fred') (a + 2)"), 7);
    },
    fullParse6: function() {
      return assertEq(runLsr("\\\\\n  a = 3\n  .\n  a"), 3);
    },
    fullParse7: function() {
      assertEq(String(runLsr("simpleScanLine '\\\\\n  a = 3\n  .\n  a'")), 'Cons[Token("\\\\", 0) Parens(1, 9, Cons[Token("a", 4) Token("=", 6) Token("3", 8)]) Token(".", 12) Token("a", 16)]');
      assertEq(String(runLsr("simpleScanLine 'head\n  cons\n    1\n    nil'")), 'Cons[Token("head", 0) Parens(4, 25, Cons[Token("cons", 7) Token("1", 16) Token("nil", 22)])]');
      return assertEq(runLsr("head\n  cons\n    1\n    nil"), 1);
    }
  });

  process.exit(T.totalFailures);

}).call(this);

/*
//@ sourceMappingURL=testParser.map
*/
