#!/bin/sh
STACK=3000
STACK=4000
STACK=1000
#STACK=10000
NODE=node

if [ "$1" == -D ]; then
    NODE=node-debug
    shift
fi

if [ -n "$(expr "$(uname -s)" : '\(CYGWIN\|WIN\)')" ]; then
    echo CYGWIN
    dir=$(echo $(dirname $(cygpath -a -d $0)) | sed 's/\\/\//g')
    build=$(echo $(dirname $dir)/build | sed 's/\\/\//g')
    export NODE_PATH="$build;$build/leisure;$build/lib;$build/node_modules;$dir/build/node_modules;$dir/build/lib"
    echo NODE_PATH="'$NODE_PATH'"
    NODE=$dir/build/runNode
    #echo $NODE --stack-size=$STACK $dir/build/src/runRepl "$@"
    $NODE --stack-size=$STACK $dir/build/src/runRepl "$@"
    #$NODE $dir/build/src/runRepl "$@"
else
    dir=$(cd "$(dirname $0)"; pwd -P)
    build=$(dirname $dir)/build
    inst=$dir/leisure/build
    export NODE_PATH="$build:$build/leisure:$build/lib:$build/node_modules:$dir/build/node_modules:$dir/build/lib"
    NODE=$dir/build/runNode
    $NODE --stack-size=$STACK $dir/build/src/runRepl "$@"
fi
